# Imported important modules

In [11]:
from numpy import mean
from numpy import std
from numpy.random import randn
from numpy.random import seed
from matplotlib import pyplot
import pandas as pd
from numpy import cov
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import kendalltau
import numpy as np
import math
import plotly.graph_objects as go
import plotly.express as px
import statistics

# my written function for pearson ( no need because scipy has built in function)

In [2]:
def average(x):
    assert len(x) > 0
    return float(sum(x)) / len(x)

def pearson_def(x, y):
    assert len(x) == len(y)
    n = len(x)
    assert n > 0
    avg_x = average(x)
    avg_y = average(y)
    diffprod = 0
    xdiff2 = 0
    ydiff2 = 0
    for idx in range(n):
        xdiff = x[idx] - avg_x
        ydiff = y[idx] - avg_y
        diffprod += xdiff * ydiff
        xdiff2 += xdiff * xdiff
        ydiff2 += ydiff * ydiff

    return diffprod / math.sqrt(xdiff2 * ydiff2)

# A function for checking different times of correlations, mean, standard deviation and covariance

In [12]:
countrys = [] #country names
correlationp = [] ##pearson
correlations = [] #spearsman
correlationk = [] #kendall
commentpearson =[]
commentspearsman = []
commentkendall = []
mediantemp = []
mediannewlyaffected = []
pearp=[]
spearp=[]
kendallp=[]

def correl(bd):
    Bd1 = bd.iloc[:,10:11]
    Bd2 = bd.iloc[:,11:12]
    countrys.append(bd.iloc[0,0])
    
    X = [x[0] for x in Bd1.values.tolist()]  #list comprehension
    Y = [y[0] for y in Bd2.values.tolist()]
    print('data1: mean=%.3f stdv=%.3f' % (mean(X), std(X)))
    print('data2: mean=%.3f stdv=%.3f' % (mean(Y), std(Y)))
    
    mediantemp.append(statistics.median(X)) 
    mediannewlyaffected.append(statistics.median(Y)) 

    
    #print('my function pearson : %.5f' % pearson_def(X,Y))
    
    covariance = cov(X,Y)
    print('covarience value :')
    print( covariance)
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=X,y=Y,mode='markers',marker_color=Y)) # hover text goes here

    fig.update_layout(title='Humidity vs Affected', xaxis=dict(title='Humidity'),yaxis=dict(title='Total # of Affected'))
    
    fig.show()
    ##pyplot.scatter(Bd1, Bd2)
    #pyplot.xlabel("temparature")
    #pyplot.ylabel("Total Affected")
    #pyplot.show()
    alpha = 0.05 #setting my significant level 5 %
    corr, r = pearsonr(X,Y)
    print('Pearsons correlation: %.3f' % corr)
    correlationp.append('%.3f'%(corr))
    
    if r > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % r)
        commentpearson.append('uncorrelated')
        pearp.append('%.3f'%(r))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % r)
        commentpearson.append('correlated')
        pearp.append('%.3f'%(r))
        
    corr, p = spearmanr(X,Y)
    print('Spearmans correlation: %.3f' % corr)
    correlations.append('%.3f'%(corr))
    
    # interpret the significance
    
    if p > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % p)
        commentspearsman.append('uncorrelated')
        spearp.append('%.3f'%(p))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % p)
        commentspearsman.append('correlated')
        spearp.append('%.3f'%(p))
        
    
    coef, q = kendalltau(X,Y)
    print('Kendall correlation coefficient: %.3f' % coef)
    correlationk.append('%.3f'%(coef))
    # interpret the significance
    alpha = 0.05
    if q > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % q)
        commentkendall.append('uncorrelated')
        kendallp.append('%.3f'%(q))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % q)
        commentkendall.append('correlated')
        kendallp.append('%.3f'%(q))

    


# For all countries (New approach)
# Preparing datasets and calling functions to find out correlations

In [13]:
df = pd.read_csv('temperaturehumidity2.csv')
dfg = df.groupby('Country_name').apply(correl)
dfg.head(20)



data1: mean=55.348 stdv=15.944
data2: mean=15.957 stdv=17.682
covarience value :
[[265.7826087  -61.62055336]
 [-61.62055336 326.86166008]]


Pearsons correlation: -0.209
Samples are uncorrelated (fail to reject H0) p=0.338
Spearmans correlation: -0.210
Samples are uncorrelated (fail to reject H0) p=0.337
Kendall correlation coefficient: -0.139
Samples are uncorrelated (fail to reject H0) p=0.366
data1: mean=70.138 stdv=9.224
data2: mean=13.000 stdv=8.120
covarience value :
[[ 88.12315271 -24.89285714]
 [-24.89285714  68.28571429]]


Pearsons correlation: -0.321
Samples are uncorrelated (fail to reject H0) p=0.090
Spearmans correlation: -0.305
Samples are uncorrelated (fail to reject H0) p=0.107
Kendall correlation coefficient: -0.243
Samples are uncorrelated (fail to reject H0) p=0.071
data1: mean=65.000 stdv=10.871
data2: mean=43.121 stdv=47.868
covarience value :
[[ 121.875       196.40625   ]
 [ 196.40625    2362.92234848]]


Pearsons correlation: 0.366
Samples are correlated (reject H0) p=0.036
Spearmans correlation: 0.343
Samples are uncorrelated (fail to reject H0) p=0.051
Kendall correlation coefficient: 0.189
Samples are uncorrelated (fail to reject H0) p=0.128
data1: mean=79.727 stdv=12.326
data2: mean=23.864 stdv=12.392
covarience value :
[[159.16017316  82.72294372]
 [ 82.72294372 160.88528139]]


Pearsons correlation: 0.517
Samples are correlated (reject H0) p=0.014
Spearmans correlation: 0.498
Samples are correlated (reject H0) p=0.018
Kendall correlation coefficient: 0.359
Samples are correlated (reject H0) p=0.022
data1: mean=47.000 stdv=11.298
data2: mean=55.500 stdv=59.832
covarience value :
[[ 132.37037037  243.33333333]
 [ 243.33333333 3712.48148148]]


Pearsons correlation: 0.347
Samples are uncorrelated (fail to reject H0) p=0.070
Spearmans correlation: 0.519
Samples are correlated (reject H0) p=0.005
Kendall correlation coefficient: 0.401
Samples are correlated (reject H0) p=0.003
data1: mean=49.929 stdv=12.767
data2: mean=29.893 stdv=23.542
covarience value :
[[169.03174603 -50.71164021]
 [-50.71164021 574.76587302]]


Pearsons correlation: -0.163
Samples are uncorrelated (fail to reject H0) p=0.408
Spearmans correlation: -0.230
Samples are uncorrelated (fail to reject H0) p=0.240
Kendall correlation coefficient: -0.146
Samples are uncorrelated (fail to reject H0) p=0.284
data1: mean=66.805 stdv=11.202
data2: mean=141.171 stdv=151.460
covarience value :
[[  128.61097561   219.70914634]
 [  219.70914634 23513.64512195]]


Pearsons correlation: 0.126
Samples are uncorrelated (fail to reject H0) p=0.431
Spearmans correlation: 0.336
Samples are correlated (reject H0) p=0.032
Kendall correlation coefficient: 0.168
Samples are uncorrelated (fail to reject H0) p=0.128
data1: mean=59.150 stdv=9.161
data2: mean=307.425 stdv=312.857
covarience value :
[[ 8.60794872e+01 -5.02757692e+02]
 [-5.02757692e+02  1.00389020e+05]]


Pearsons correlation: -0.171
Samples are uncorrelated (fail to reject H0) p=0.291
Spearmans correlation: -0.125
Samples are uncorrelated (fail to reject H0) p=0.443
Kendall correlation coefficient: -0.093
Samples are uncorrelated (fail to reject H0) p=0.401
data1: mean=65.600 stdv=10.178
data2: mean=25.640 stdv=23.215
covarience value :
[[ 107.91666667 -114.775     ]
 [-114.775       561.40666667]]


Pearsons correlation: -0.466
Samples are correlated (reject H0) p=0.019
Spearmans correlation: -0.303
Samples are uncorrelated (fail to reject H0) p=0.141
Kendall correlation coefficient: -0.197
Samples are uncorrelated (fail to reject H0) p=0.174
data1: mean=64.108 stdv=7.399
data2: mean=20.432 stdv=19.631
covarience value :
[[ 56.26576577 -44.68693694]
 [-44.68693694 396.08558559]]


Pearsons correlation: -0.299
Samples are uncorrelated (fail to reject H0) p=0.072
Spearmans correlation: -0.313
Samples are uncorrelated (fail to reject H0) p=0.060
Kendall correlation coefficient: -0.236
Samples are correlated (reject H0) p=0.045
data1: mean=44.952 stdv=11.069
data2: mean=5.857 stdv=7.415
covarience value :
[[128.64761905 -17.25714286]
 [-17.25714286  57.72857143]]


Pearsons correlation: -0.200
Samples are uncorrelated (fail to reject H0) p=0.384
Spearmans correlation: -0.092
Samples are uncorrelated (fail to reject H0) p=0.693
Kendall correlation coefficient: -0.088
Samples are uncorrelated (fail to reject H0) p=0.600
data1: mean=68.842 stdv=15.045
data2: mean=36.842 stdv=47.404
covarience value :
[[ 238.91812865 -521.74853801]
 [-521.74853801 2372.02923977]]


Pearsons correlation: -0.693
Samples are correlated (reject H0) p=0.001
Spearmans correlation: -0.610
Samples are correlated (reject H0) p=0.006
Kendall correlation coefficient: -0.428
Samples are correlated (reject H0) p=0.012
data1: mean=73.865 stdv=11.971
data2: mean=562.541 stdv=576.748
covarience value :
[[ 1.47286787e+02 -5.05448048e+03]
 [-5.05448048e+03  3.41878755e+05]]


Pearsons correlation: -0.712
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.551
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.371
Samples are correlated (reject H0) p=0.001
data1: mean=74.261 stdv=3.779
data2: mean=7.957 stdv=6.423
covarience value :
[[14.92885375  4.87549407]
 [ 4.87549407 43.13438735]]


Pearsons correlation: 0.192
Samples are uncorrelated (fail to reject H0) p=0.380
Spearmans correlation: 0.066
Samples are uncorrelated (fail to reject H0) p=0.766
Kendall correlation coefficient: 0.056
Samples are uncorrelated (fail to reject H0) p=0.726
data1: mean=81.033 stdv=11.520
data2: mean=22.467 stdv=20.638
covarience value :
[[ 137.27471264 -120.42988506]
 [-120.42988506  440.60229885]]


Pearsons correlation: -0.490
Samples are correlated (reject H0) p=0.006
Spearmans correlation: -0.366
Samples are correlated (reject H0) p=0.046
Kendall correlation coefficient: -0.263
Samples are correlated (reject H0) p=0.047
data1: mean=82.424 stdv=3.931
data2: mean=368.515 stdv=409.466
covarience value :
[[1.59393939e+01 7.00962121e+02]
 [7.00962121e+02 1.72902195e+05]]


Pearsons correlation: 0.422
Samples are correlated (reject H0) p=0.014
Spearmans correlation: 0.394
Samples are correlated (reject H0) p=0.023
Kendall correlation coefficient: 0.288
Samples are correlated (reject H0) p=0.023
data1: mean=82.720 stdv=3.040
data2: mean=5.400 stdv=5.418
covarience value :
[[ 9.62666667  5.11666667]
 [ 5.11666667 30.58333333]]


Pearsons correlation: 0.298
Samples are uncorrelated (fail to reject H0) p=0.148
Spearmans correlation: 0.084
Samples are uncorrelated (fail to reject H0) p=0.689
Kendall correlation coefficient: 0.066
Samples are uncorrelated (fail to reject H0) p=0.667
data1: mean=75.741 stdv=13.772
data2: mean=20.333 stdv=10.805
covarience value :
[[196.96866097  24.58974359]
 [ 24.58974359 121.23076923]]


Pearsons correlation: 0.159
Samples are uncorrelated (fail to reject H0) p=0.428
Spearmans correlation: 0.220
Samples are uncorrelated (fail to reject H0) p=0.271
Kendall correlation coefficient: 0.183
Samples are uncorrelated (fail to reject H0) p=0.187
data1: mean=15.583 stdv=8.911
data2: mean=15.167 stdv=9.095
covarience value :
[[82.86231884 26.02898551]
 [26.02898551 86.31884058]]


Pearsons correlation: 0.308
Samples are uncorrelated (fail to reject H0) p=0.143
Spearmans correlation: 0.416
Samples are correlated (reject H0) p=0.043
Kendall correlation coefficient: 0.254
Samples are uncorrelated (fail to reject H0) p=0.093
data1: mean=81.500 stdv=2.141
data2: mean=1.167 stdv=0.373
covarience value :
[[ 5.5        -0.1       ]
 [-0.1         0.16666667]]


Pearsons correlation: -0.104
Samples are uncorrelated (fail to reject H0) p=0.844
Spearmans correlation: -0.133
Samples are uncorrelated (fail to reject H0) p=0.802
Kendall correlation coefficient: -0.120
Samples are uncorrelated (fail to reject H0) p=0.766
data1: mean=55.421 stdv=3.066
data2: mean=5.947 stdv=8.256
covarience value :
[[ 9.92397661 -2.30994152]
 [-2.30994152 71.94152047]]


Pearsons correlation: -0.086
Samples are uncorrelated (fail to reject H0) p=0.725
Spearmans correlation: -0.102
Samples are uncorrelated (fail to reject H0) p=0.678
Kendall correlation coefficient: -0.054
Samples are uncorrelated (fail to reject H0) p=0.770
data1: mean=86.478 stdv=9.555
data2: mean=359.978 stdv=557.055
covarience value :
[[ 9.33217391e+01 -1.88692271e+03]
 [-1.88692271e+03  3.17206200e+05]]


Pearsons correlation: -0.347
Samples are correlated (reject H0) p=0.018
Spearmans correlation: -0.437
Samples are correlated (reject H0) p=0.002
Kendall correlation coefficient: -0.316
Samples are correlated (reject H0) p=0.003
data1: mean=40.588 stdv=9.268
data2: mean=202.647 stdv=172.047
covarience value :
[[   88.49197861   321.51693405]
 [  321.51693405 30497.02317291]]


Pearsons correlation: 0.196
Samples are uncorrelated (fail to reject H0) p=0.267
Spearmans correlation: 0.220
Samples are uncorrelated (fail to reject H0) p=0.211
Kendall correlation coefficient: 0.161
Samples are uncorrelated (fail to reject H0) p=0.186
data1: mean=37.803 stdv=16.462
data2: mean=1103.985 stdv=2221.642
covarience value :
[[2.75175991e+02 4.48887389e+03]
 [4.48887389e+03 5.01162694e+06]]


Pearsons correlation: 0.121
Samples are uncorrelated (fail to reject H0) p=0.334
Spearmans correlation: 0.330
Samples are correlated (reject H0) p=0.007
Kendall correlation coefficient: 0.224
Samples are correlated (reject H0) p=0.008
data1: mean=81.893 stdv=4.065
data2: mean=56.393 stdv=45.231
covarience value :
[[  17.13624339   92.63624339]
 [  92.63624339 2121.58068783]]


Pearsons correlation: 0.486
Samples are correlated (reject H0) p=0.009
Spearmans correlation: 0.473
Samples are correlated (reject H0) p=0.011
Kendall correlation coefficient: 0.303
Samples are correlated (reject H0) p=0.027
data1: mean=68.500 stdv=5.315
data2: mean=7.500 stdv=8.480
covarience value :
[[33.9 12.9]
 [12.9 86.3]]


Pearsons correlation: 0.238
Samples are uncorrelated (fail to reject H0) p=0.649
Spearmans correlation: 0.290
Samples are uncorrelated (fail to reject H0) p=0.577
Kendall correlation coefficient: 0.276
Samples are uncorrelated (fail to reject H0) p=0.444
data1: mean=72.105 stdv=6.504
data2: mean=8.474 stdv=6.885
covarience value :
[[44.65497076 -3.94152047]
 [-3.94152047 50.04093567]]


Pearsons correlation: -0.083
Samples are uncorrelated (fail to reject H0) p=0.734
Spearmans correlation: -0.046
Samples are uncorrelated (fail to reject H0) p=0.853
Kendall correlation coefficient: -0.055
Samples are uncorrelated (fail to reject H0) p=0.750
data1: mean=71.567 stdv=5.445
data2: mean=15.567 stdv=9.608
covarience value :
[[30.66781609 -8.26321839]
 [-8.26321839 95.4954023 ]]


Pearsons correlation: -0.153
Samples are uncorrelated (fail to reject H0) p=0.421
Spearmans correlation: -0.269
Samples are uncorrelated (fail to reject H0) p=0.151
Kendall correlation coefficient: -0.200
Samples are uncorrelated (fail to reject H0) p=0.139
data1: mean=70.842 stdv=6.209
data2: mean=17.000 stdv=19.309
covarience value :
[[ 40.69590643   2.5       ]
 [  2.5        393.55555556]]


Pearsons correlation: 0.020
Samples are uncorrelated (fail to reject H0) p=0.936
Spearmans correlation: 0.126
Samples are uncorrelated (fail to reject H0) p=0.606
Kendall correlation coefficient: 0.098
Samples are uncorrelated (fail to reject H0) p=0.571
data1: mean=63.417 stdv=10.391
data2: mean=33.944 stdv=31.089
covarience value :
[[111.05       -76.74761905]
 [-76.74761905 994.11111111]]


Pearsons correlation: -0.231
Samples are uncorrelated (fail to reject H0) p=0.175
Spearmans correlation: -0.283
Samples are uncorrelated (fail to reject H0) p=0.095
Kendall correlation coefficient: -0.199
Samples are uncorrelated (fail to reject H0) p=0.095
data1: mean=72.478 stdv=3.308
data2: mean=15.217 stdv=11.843
covarience value :
[[ 11.44268775  -9.6541502 ]
 [ -9.6541502  146.63241107]]


Pearsons correlation: -0.236
Samples are uncorrelated (fail to reject H0) p=0.279
Spearmans correlation: -0.107
Samples are uncorrelated (fail to reject H0) p=0.628
Kendall correlation coefficient: -0.121
Samples are uncorrelated (fail to reject H0) p=0.438
data1: mean=70.462 stdv=8.215
data2: mean=17.885 stdv=13.305
covarience value :
[[ 70.17846154 -48.34461538]
 [-48.34461538 184.10615385]]


Pearsons correlation: -0.425
Samples are correlated (reject H0) p=0.030
Spearmans correlation: -0.430
Samples are correlated (reject H0) p=0.028
Kendall correlation coefficient: -0.268
Samples are uncorrelated (fail to reject H0) p=0.060
data1: mean=76.694 stdv=10.181
data2: mean=135.417 stdv=104.070
covarience value :
[[  106.61825397  -643.21190476]
 [ -643.21190476 11139.96428571]]


Pearsons correlation: -0.590
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.435
Samples are correlated (reject H0) p=0.008
Kendall correlation coefficient: -0.273
Samples are correlated (reject H0) p=0.021
data1: mean=77.739 stdv=3.378
data2: mean=79.478 stdv=67.532
covarience value :
[[  11.92885375  -67.50592885]
 [ -67.50592885 4767.80632411]]


Pearsons correlation: -0.283
Samples are uncorrelated (fail to reject H0) p=0.191
Spearmans correlation: -0.419
Samples are correlated (reject H0) p=0.046
Kendall correlation coefficient: -0.323
Samples are correlated (reject H0) p=0.037
data1: mean=76.033 stdv=3.710
data2: mean=124.900 stdv=126.702
covarience value :
[[ 1.42402299e+01 -1.05582759e+02]
 [-1.05582759e+02  1.66068517e+04]]


Pearsons correlation: -0.217
Samples are uncorrelated (fail to reject H0) p=0.249
Spearmans correlation: -0.141
Samples are uncorrelated (fail to reject H0) p=0.456
Kendall correlation coefficient: -0.112
Samples are uncorrelated (fail to reject H0) p=0.399
data1: mean=49.182 stdv=12.878
data2: mean=40.061 stdv=35.728
covarience value :
[[ 171.02840909 -160.13636364]
 [-160.13636364 1316.37121212]]


Pearsons correlation: -0.337
Samples are uncorrelated (fail to reject H0) p=0.055
Spearmans correlation: -0.327
Samples are uncorrelated (fail to reject H0) p=0.063
Kendall correlation coefficient: -0.223
Samples are uncorrelated (fail to reject H0) p=0.074
data1: mean=77.419 stdv=12.393
data2: mean=35.742 stdv=31.173
covarience value :
[[1.58718280e+02 8.78494624e-01]
 [8.78494624e-01 1.00413118e+03]]


Pearsons correlation: 0.002
Samples are uncorrelated (fail to reject H0) p=0.991
Spearmans correlation: -0.018
Samples are uncorrelated (fail to reject H0) p=0.923
Kendall correlation coefficient: -0.013
Samples are uncorrelated (fail to reject H0) p=0.918
data1: mean=75.944 stdv=13.818
data2: mean=60.500 stdv=60.686
covarience value :
[[ 196.3968254    14.57142857]
 [  14.57142857 3788.02857143]]


Pearsons correlation: 0.017
Samples are uncorrelated (fail to reject H0) p=0.922
Spearmans correlation: 0.099
Samples are uncorrelated (fail to reject H0) p=0.567
Kendall correlation coefficient: 0.065
Samples are uncorrelated (fail to reject H0) p=0.585
data1: mean=68.614 stdv=10.798
data2: mean=1712.227 stdv=1889.974
covarience value :
[[ 1.19312368e+02 -7.44614271e+03]
 [-7.44614271e+03  3.65506962e+06]]


Pearsons correlation: -0.357
Samples are correlated (reject H0) p=0.018
Spearmans correlation: -0.280
Samples are uncorrelated (fail to reject H0) p=0.065
Kendall correlation coefficient: -0.198
Samples are uncorrelated (fail to reject H0) p=0.062
data1: mean=59.567 stdv=15.106
data2: mean=6.267 stdv=4.892
covarience value :
[[236.04712644   6.05057471]
 [  6.05057471  24.75402299]]


Pearsons correlation: 0.079
Samples are uncorrelated (fail to reject H0) p=0.678
Spearmans correlation: 0.164
Samples are uncorrelated (fail to reject H0) p=0.387
Kendall correlation coefficient: 0.089
Samples are uncorrelated (fail to reject H0) p=0.505
data1: mean=69.938 stdv=12.789
data2: mean=2153.521 stdv=2386.795
covarience value :
[[ 1.67038564e+02 -2.05357753e+04]
 [-2.05357753e+04  5.81800000e+06]]


Pearsons correlation: -0.659
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.580
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.424
Samples are correlated (reject H0) p=0.000
data1: mean=73.842 stdv=1.981
data2: mean=11.263 stdv=12.669
covarience value :
[[  4.14035088  -5.62280702]
 [ -5.62280702 169.42690058]]


Pearsons correlation: -0.212
Samples are uncorrelated (fail to reject H0) p=0.383
Spearmans correlation: -0.333
Samples are uncorrelated (fail to reject H0) p=0.163
Kendall correlation coefficient: -0.278
Samples are uncorrelated (fail to reject H0) p=0.133
data1: mean=77.412 stdv=11.056
data2: mean=51.618 stdv=37.021
covarience value :
[[ 125.94652406 -141.71657754]
 [-141.71657754 1412.12210339]]


Pearsons correlation: -0.336
Samples are uncorrelated (fail to reject H0) p=0.052
Spearmans correlation: -0.334
Samples are uncorrelated (fail to reject H0) p=0.053
Kendall correlation coefficient: -0.264
Samples are correlated (reject H0) p=0.030
data1: mean=73.250 stdv=2.976
data2: mean=10.667 stdv=10.562
covarience value :
[[  9.65909091   0.54545455]
 [  0.54545455 121.6969697 ]]


Pearsons correlation: 0.016
Samples are uncorrelated (fail to reject H0) p=0.961
Spearmans correlation: -0.071
Samples are uncorrelated (fail to reject H0) p=0.826
Kendall correlation coefficient: -0.032
Samples are uncorrelated (fail to reject H0) p=0.889
data1: mean=66.136 stdv=6.211
data2: mean=13.545 stdv=14.080
covarience value :
[[ 40.40909091 -30.93506494]
 [-30.93506494 207.68831169]]


Pearsons correlation: -0.338
Samples are uncorrelated (fail to reject H0) p=0.124
Spearmans correlation: -0.368
Samples are uncorrelated (fail to reject H0) p=0.092
Kendall correlation coefficient: -0.285
Samples are uncorrelated (fail to reject H0) p=0.076
data1: mean=58.200 stdv=10.713
data2: mean=24.800 stdv=19.446
covarience value :
[[ 118.71724138 -136.88965517]
 [-136.88965517  391.2       ]]


Pearsons correlation: -0.635
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.640
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.430
Samples are correlated (reject H0) p=0.001
data1: mean=73.405 stdv=7.713
data2: mean=42.216 stdv=31.587
covarience value :
[[  61.13663664   27.99324324]
 [  27.99324324 1025.45195195]]


Pearsons correlation: 0.112
Samples are uncorrelated (fail to reject H0) p=0.510
Spearmans correlation: 0.048
Samples are uncorrelated (fail to reject H0) p=0.776
Kendall correlation coefficient: 0.024
Samples are uncorrelated (fail to reject H0) p=0.834
data1: mean=43.378 stdv=10.440
data2: mean=129.108 stdv=240.423
covarience value :
[[  112.01951952  -455.0975976 ]
 [ -455.0975976  59408.93243243]]


Pearsons correlation: -0.176
Samples are uncorrelated (fail to reject H0) p=0.296
Spearmans correlation: -0.406
Samples are correlated (reject H0) p=0.013
Kendall correlation coefficient: -0.289
Samples are correlated (reject H0) p=0.013
data1: mean=84.032 stdv=4.068
data2: mean=80.355 stdv=60.159
covarience value :
[[  17.09892473  -31.54516129]
 [ -31.54516129 3739.76989247]]


Pearsons correlation: -0.125
Samples are uncorrelated (fail to reject H0) p=0.504
Spearmans correlation: -0.087
Samples are uncorrelated (fail to reject H0) p=0.640
Kendall correlation coefficient: -0.051
Samples are uncorrelated (fail to reject H0) p=0.694
data1: mean=43.417 stdv=14.329
data2: mean=1260.417 stdv=1020.358
covarience value :
[[2.09695035e+02 2.70886525e+02]
 [2.70886525e+02 1.06328246e+06]]


Pearsons correlation: 0.018
Samples are uncorrelated (fail to reject H0) p=0.903
Spearmans correlation: 0.001
Samples are uncorrelated (fail to reject H0) p=0.993
Kendall correlation coefficient: -0.002
Samples are uncorrelated (fail to reject H0) p=0.986
data1: mean=40.216 stdv=13.165
data2: mean=27.865 stdv=24.624
covarience value :
[[178.11861862 -58.35885886]
 [-58.35885886 623.17567568]]


Pearsons correlation: -0.175
Samples are uncorrelated (fail to reject H0) p=0.300
Spearmans correlation: -0.168
Samples are uncorrelated (fail to reject H0) p=0.320
Kendall correlation coefficient: -0.119
Samples are uncorrelated (fail to reject H0) p=0.312
data1: mean=79.062 stdv=4.937
data2: mean=167.625 stdv=140.360
covarience value :
[[   25.15725806   110.02419355]
 [  110.02419355 20336.5       ]]


Pearsons correlation: 0.154
Samples are uncorrelated (fail to reject H0) p=0.401
Spearmans correlation: 0.126
Samples are uncorrelated (fail to reject H0) p=0.492
Kendall correlation coefficient: 0.081
Samples are uncorrelated (fail to reject H0) p=0.525
data1: mean=67.625 stdv=10.119
data2: mean=222.600 stdv=284.840
covarience value :
[[  105.00961538 -1222.30769231]
 [-1222.30769231 83214.24615385]]


Pearsons correlation: -0.413
Samples are correlated (reject H0) p=0.008
Spearmans correlation: -0.314
Samples are correlated (reject H0) p=0.048
Kendall correlation coefficient: -0.232
Samples are correlated (reject H0) p=0.039
data1: mean=62.915 stdv=10.120
data2: mean=2820.106 stdv=2194.295
covarience value :
[[ 1.04644773e+02 -6.39325162e+03]
 [-6.39325162e+03  4.91960118e+06]]


Pearsons correlation: -0.282
Samples are uncorrelated (fail to reject H0) p=0.055
Spearmans correlation: -0.292
Samples are correlated (reject H0) p=0.046
Kendall correlation coefficient: -0.197
Samples are uncorrelated (fail to reject H0) p=0.054
data1: mean=77.556 stdv=13.037
data2: mean=67.389 stdv=107.842
covarience value :
[[  173.1572327    375.3836478 ]
 [  375.3836478  11849.41194969]]


Pearsons correlation: 0.262
Samples are uncorrelated (fail to reject H0) p=0.056
Spearmans correlation: 0.189
Samples are uncorrelated (fail to reject H0) p=0.171
Kendall correlation coefficient: 0.129
Samples are uncorrelated (fail to reject H0) p=0.176
data1: mean=66.435 stdv=15.980
data2: mean=15.174 stdv=8.805
covarience value :
[[266.98418972  -4.57905138]
 [ -4.57905138  81.05928854]]


Pearsons correlation: -0.031
Samples are uncorrelated (fail to reject H0) p=0.888
Spearmans correlation: -0.118
Samples are uncorrelated (fail to reject H0) p=0.591
Kendall correlation coefficient: -0.080
Samples are uncorrelated (fail to reject H0) p=0.596
data1: mean=87.760 stdv=7.538
data2: mean=26.480 stdv=25.022
covarience value :
[[ 59.19        44.57833333]
 [ 44.57833333 652.17666667]]


Pearsons correlation: 0.227
Samples are uncorrelated (fail to reject H0) p=0.275
Spearmans correlation: 0.203
Samples are uncorrelated (fail to reject H0) p=0.331
Kendall correlation coefficient: 0.123
Samples are uncorrelated (fail to reject H0) p=0.398
data1: mean=65.931 stdv=14.583
data2: mean=177.121 stdv=203.348
covarience value :
[[ 2.16381125e+02 -2.80617060e+01]
 [-2.80617060e+01  4.20760378e+04]]


Pearsons correlation: -0.009
Samples are uncorrelated (fail to reject H0) p=0.945
Spearmans correlation: -0.033
Samples are uncorrelated (fail to reject H0) p=0.806
Kendall correlation coefficient: -0.011
Samples are uncorrelated (fail to reject H0) p=0.909
data1: mean=51.000 stdv=9.539
data2: mean=18.472 stdv=23.826
covarience value :
[[ 93.6         55.4       ]
 [ 55.4        583.91349206]]


Pearsons correlation: 0.237
Samples are uncorrelated (fail to reject H0) p=0.164
Spearmans correlation: 0.015
Samples are uncorrelated (fail to reject H0) p=0.929
Kendall correlation coefficient: 0.002
Samples are uncorrelated (fail to reject H0) p=0.989
data1: mean=56.312 stdv=19.025
data2: mean=13.500 stdv=16.190
covarience value :
[[386.09583333 -63.03333333]
 [-63.03333333 279.6       ]]


Pearsons correlation: -0.192
Samples are uncorrelated (fail to reject H0) p=0.477
Spearmans correlation: 0.056
Samples are uncorrelated (fail to reject H0) p=0.838
Kendall correlation coefficient: -0.017
Samples are uncorrelated (fail to reject H0) p=0.927
data1: mean=72.733 stdv=12.439
data2: mean=18.067 stdv=12.936
covarience value :
[[160.06436782 -62.25747126]
 [-62.25747126 173.09885057]]


Pearsons correlation: -0.374
Samples are correlated (reject H0) p=0.042
Spearmans correlation: -0.347
Samples are uncorrelated (fail to reject H0) p=0.060
Kendall correlation coefficient: -0.254
Samples are uncorrelated (fail to reject H0) p=0.055
data1: mean=67.059 stdv=8.200
data2: mean=15.912 stdv=12.876
covarience value :
[[ 69.26916221 -11.44919786]
 [-11.44919786 170.81016043]]


Pearsons correlation: -0.105
Samples are uncorrelated (fail to reject H0) p=0.554
Spearmans correlation: 0.023
Samples are uncorrelated (fail to reject H0) p=0.898
Kendall correlation coefficient: 0.015
Samples are uncorrelated (fail to reject H0) p=0.905
data1: mean=71.370 stdv=14.955
data2: mean=31.222 stdv=23.638
covarience value :
[[ 232.24216524 -241.77777778]
 [-241.77777778  580.25641026]]


Pearsons correlation: -0.659
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.724
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.535
Samples are correlated (reject H0) p=0.000
data1: mean=79.000 stdv=12.730
data2: mean=91.710 stdv=75.044
covarience value :
[[ 167.46666667 -276.73333333]
 [-276.73333333 5819.34623656]]


Pearsons correlation: -0.280
Samples are uncorrelated (fail to reject H0) p=0.127
Spearmans correlation: -0.328
Samples are uncorrelated (fail to reject H0) p=0.071
Kendall correlation coefficient: -0.243
Samples are uncorrelated (fail to reject H0) p=0.063
data1: mean=72.000 stdv=5.367
data2: mean=90.119 stdv=76.365
covarience value :
[[  29.51219512  119.51219512]
 [ 119.51219512 5973.81475029]]


Pearsons correlation: 0.285
Samples are uncorrelated (fail to reject H0) p=0.068
Spearmans correlation: 0.323
Samples are correlated (reject H0) p=0.037
Kendall correlation coefficient: 0.240
Samples are correlated (reject H0) p=0.030
data1: mean=75.111 stdv=5.977
data2: mean=8.926 stdv=5.395
covarience value :
[[37.1025641   3.97008547]
 [ 3.97008547 30.22507123]]


Pearsons correlation: 0.119
Samples are uncorrelated (fail to reject H0) p=0.556
Spearmans correlation: 0.127
Samples are uncorrelated (fail to reject H0) p=0.527
Kendall correlation coefficient: 0.083
Samples are uncorrelated (fail to reject H0) p=0.557
data1: mean=40.200 stdv=8.424
data2: mean=1.200 stdv=0.400
covarience value :
[[88.7  1.7]
 [ 1.7  0.2]]


Pearsons correlation: 0.404
Samples are uncorrelated (fail to reject H0) p=0.500
Spearmans correlation: 0.363
Samples are uncorrelated (fail to reject H0) p=0.548
Kendall correlation coefficient: 0.333
Samples are uncorrelated (fail to reject H0) p=0.468
data1: mean=80.947 stdv=5.083
data2: mean=12.842 stdv=8.375
covarience value :
[[ 27.2748538  -17.1754386 ]
 [-17.1754386   74.02923977]]


Pearsons correlation: -0.382
Samples are uncorrelated (fail to reject H0) p=0.106
Spearmans correlation: -0.431
Samples are uncorrelated (fail to reject H0) p=0.065
Kendall correlation coefficient: -0.315
Samples are uncorrelated (fail to reject H0) p=0.070
data1: mean=38.062 stdv=9.769
data2: mean=76.219 stdv=78.273
covarience value :
[[  98.51209677 -310.65927419]
 [-310.65927419 6324.30544355]]


Pearsons correlation: -0.394
Samples are correlated (reject H0) p=0.026
Spearmans correlation: -0.206
Samples are uncorrelated (fail to reject H0) p=0.259
Kendall correlation coefficient: -0.136
Samples are uncorrelated (fail to reject H0) p=0.282
data1: mean=58.480 stdv=10.789
data2: mean=38.600 stdv=40.161
covarience value :
[[ 121.26       -157.675     ]
 [-157.675      1680.08333333]]


Pearsons correlation: -0.349
Samples are uncorrelated (fail to reject H0) p=0.087
Spearmans correlation: -0.465
Samples are correlated (reject H0) p=0.019
Kendall correlation coefficient: -0.321
Samples are correlated (reject H0) p=0.027
data1: mean=65.789 stdv=11.214
data2: mean=12.263 stdv=8.577
covarience value :
[[132.73099415   2.00292398]
 [  2.00292398  77.64912281]]


Pearsons correlation: 0.020
Samples are uncorrelated (fail to reject H0) p=0.936
Spearmans correlation: 0.070
Samples are uncorrelated (fail to reject H0) p=0.776
Kendall correlation coefficient: 0.066
Samples are uncorrelated (fail to reject H0) p=0.699
data1: mean=73.667 stdv=7.743
data2: mean=37.333 stdv=35.713
covarience value :
[[  62.02298851   75.28735632]
 [  75.28735632 1319.40229885]]


Pearsons correlation: 0.263
Samples are uncorrelated (fail to reject H0) p=0.160
Spearmans correlation: 0.219
Samples are uncorrelated (fail to reject H0) p=0.245
Kendall correlation coefficient: 0.151
Samples are uncorrelated (fail to reject H0) p=0.257
data1: mean=74.816 stdv=10.872
data2: mean=498.053 stdv=432.032
covarience value :
[[ 1.21397582e+02 -2.64236842e+03]
 [-2.64236842e+03  1.91696376e+05]]


Pearsons correlation: -0.548
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.391
Samples are correlated (reject H0) p=0.015
Kendall correlation coefficient: -0.238
Samples are correlated (reject H0) p=0.038
data1: mean=76.692 stdv=6.638
data2: mean=42.538 stdv=34.070
covarience value :
[[  45.82153846  -54.50769231]
 [ -54.50769231 1207.21846154]]


Pearsons correlation: -0.232
Samples are uncorrelated (fail to reject H0) p=0.255
Spearmans correlation: -0.222
Samples are uncorrelated (fail to reject H0) p=0.276
Kendall correlation coefficient: -0.150
Samples are uncorrelated (fail to reject H0) p=0.297
data1: mean=32.909 stdv=15.057
data2: mean=10.818 stdv=9.423
covarience value :
[[237.51515152  59.17316017]
 [ 59.17316017  93.01298701]]


Pearsons correlation: 0.398
Samples are uncorrelated (fail to reject H0) p=0.067
Spearmans correlation: 0.406
Samples are uncorrelated (fail to reject H0) p=0.061
Kendall correlation coefficient: 0.310
Samples are correlated (reject H0) p=0.050
data1: mean=77.577 stdv=10.835
data2: mean=21.923 stdv=16.518
covarience value :
[[122.09384615 -36.43384615]
 [-36.43384615 283.75384615]]


Pearsons correlation: -0.196
Samples are uncorrelated (fail to reject H0) p=0.338
Spearmans correlation: -0.276
Samples are uncorrelated (fail to reject H0) p=0.173
Kendall correlation coefficient: -0.168
Samples are uncorrelated (fail to reject H0) p=0.233
data1: mean=77.000 stdv=12.712
data2: mean=146.625 stdv=102.788
covarience value :
[[  165.74358974   176.23076923]
 [  176.23076923 10836.18910256]]


Pearsons correlation: 0.131
Samples are uncorrelated (fail to reject H0) p=0.419
Spearmans correlation: 0.083
Samples are uncorrelated (fail to reject H0) p=0.612
Kendall correlation coefficient: 0.021
Samples are uncorrelated (fail to reject H0) p=0.852
data1: mean=56.138 stdv=11.135
data2: mean=11.414 stdv=8.755
covarience value :
[[128.408867    27.1908867 ]
 [ 27.1908867   79.39408867]]


Pearsons correlation: 0.269
Samples are uncorrelated (fail to reject H0) p=0.158
Spearmans correlation: 0.244
Samples are uncorrelated (fail to reject H0) p=0.202
Kendall correlation coefficient: 0.167
Samples are uncorrelated (fail to reject H0) p=0.219
data1: mean=58.250 stdv=12.183
data2: mean=117.688 stdv=127.650
covarience value :
[[  153.22580645   565.33870968]
 [  565.33870968 16820.09274194]]


Pearsons correlation: 0.352
Samples are correlated (reject H0) p=0.048
Spearmans correlation: 0.348
Samples are uncorrelated (fail to reject H0) p=0.051
Kendall correlation coefficient: 0.244
Samples are uncorrelated (fail to reject H0) p=0.053
data1: mean=74.577 stdv=1.472
data2: mean=76.462 stdv=64.695
covarience value :
[[ 2.25384615e+00 -5.51169231e+01]
 [-5.51169231e+01  4.35289846e+03]]


Pearsons correlation: -0.556
Samples are correlated (reject H0) p=0.003
Spearmans correlation: -0.555
Samples are correlated (reject H0) p=0.003
Kendall correlation coefficient: -0.412
Samples are correlated (reject H0) p=0.006
data1: mean=75.500 stdv=3.500
data2: mean=1.000 stdv=0.000
covarience value :
[[24.5  0. ]
 [ 0.   0. ]]


C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\stats.py:3508: PearsonRConstantInputWarning:

An input array is constant; the correlation coefficent is not defined.

C:\Users\USER\.conda\envs\DAND\lib\site-packages\numpy\lib\function_base.py:2534: RuntimeWarning:

invalid value encountered in true_divide

C:\Users\USER\.conda\envs\DAND\lib\site-packages\numpy\lib\function_base.py:2535: RuntimeWarning:

invalid value encountered in true_divide

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning:

invalid value encountered in greater

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning:

invalid value encountered in less

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning:

invalid value encountered in less_equal



Pearsons correlation: nan
Samples are correlated (reject H0) p=nan
Spearmans correlation: nan
Samples are correlated (reject H0) p=nan
Kendall correlation coefficient: nan
Samples are correlated (reject H0) p=nan
data1: mean=44.217 stdv=11.743
data2: mean=4.913 stdv=3.586
covarience value :
[[144.17786561   4.33794466]
 [  4.33794466  13.44664032]]


Pearsons correlation: 0.099
Samples are uncorrelated (fail to reject H0) p=0.655
Spearmans correlation: 0.246
Samples are uncorrelated (fail to reject H0) p=0.257
Kendall correlation coefficient: 0.162
Samples are uncorrelated (fail to reject H0) p=0.306
data1: mean=74.345 stdv=3.506
data2: mean=88.310 stdv=112.233
covarience value :
[[1.27339901e+01 1.84963054e+01]
 [1.84963054e+01 1.30460788e+04]]


Pearsons correlation: 0.045
Samples are uncorrelated (fail to reject H0) p=0.815
Spearmans correlation: 0.090
Samples are uncorrelated (fail to reject H0) p=0.643
Kendall correlation coefficient: 0.044
Samples are uncorrelated (fail to reject H0) p=0.748
data1: mean=64.441 stdv=1.988
data2: mean=107.618 stdv=139.452
covarience value :
[[ 4.07219251e+00 -1.13129234e+02]
 [-1.13129234e+02  2.00362433e+04]]


Pearsons correlation: -0.396
Samples are correlated (reject H0) p=0.020
Spearmans correlation: -0.393
Samples are correlated (reject H0) p=0.021
Kendall correlation coefficient: -0.260
Samples are correlated (reject H0) p=0.041
data1: mean=62.312 stdv=14.266
data2: mean=137.906 stdv=131.714
covarience value :
[[  210.09274194 -1442.80846774]
 [-1442.80846774 17908.21673387]]


Pearsons correlation: -0.744
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.744
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.572
Samples are correlated (reject H0) p=0.000
data1: mean=71.156 stdv=6.865
data2: mean=366.562 stdv=329.980
covarience value :
[[ 4.86522177e+01 -4.94864919e+02]
 [-4.94864919e+02  1.12399222e+05]]


Pearsons correlation: -0.212
Samples are uncorrelated (fail to reject H0) p=0.245
Spearmans correlation: -0.147
Samples are uncorrelated (fail to reject H0) p=0.421
Kendall correlation coefficient: -0.117
Samples are uncorrelated (fail to reject H0) p=0.353
data1: mean=56.375 stdv=7.833
data2: mean=57.250 stdv=79.227
covarience value :
[[  63.33870968  -38.67741935]
 [ -38.67741935 6479.35483871]]


Pearsons correlation: -0.060
Samples are uncorrelated (fail to reject H0) p=0.743
Spearmans correlation: -0.010
Samples are uncorrelated (fail to reject H0) p=0.957
Kendall correlation coefficient: 0.014
Samples are uncorrelated (fail to reject H0) p=0.909
data1: mean=57.676 stdv=11.499
data2: mean=119.324 stdv=129.406
covarience value :
[[  136.2254902   -609.07397504]
 [ -609.07397504 17253.43761141]]


Pearsons correlation: -0.397
Samples are correlated (reject H0) p=0.020
Spearmans correlation: -0.368
Samples are correlated (reject H0) p=0.032
Kendall correlation coefficient: -0.263
Samples are correlated (reject H0) p=0.030
data1: mean=73.871 stdv=16.547
data2: mean=204.548 stdv=261.676
covarience value :
[[  282.91612903 -3548.62688172]
 [-3548.62688172 70756.98924731]]


Pearsons correlation: -0.793
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.840
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.659
Samples are correlated (reject H0) p=0.000
data1: mean=86.000 stdv=3.050
data2: mean=5.250 stdv=4.311
covarience value :
[[ 9.78947368  2.78947368]
 [ 2.78947368 19.56578947]]


Pearsons correlation: 0.202
Samples are uncorrelated (fail to reject H0) p=0.394
Spearmans correlation: 0.127
Samples are uncorrelated (fail to reject H0) p=0.595
Kendall correlation coefficient: 0.121
Samples are uncorrelated (fail to reject H0) p=0.485
data1: mean=66.640 stdv=8.163
data2: mean=10.640 stdv=7.413
covarience value :
[[69.40666667 -3.17666667]
 [-3.17666667 57.24      ]]


Pearsons correlation: -0.050
Samples are uncorrelated (fail to reject H0) p=0.811
Spearmans correlation: -0.098
Samples are uncorrelated (fail to reject H0) p=0.641
Kendall correlation coefficient: -0.062
Samples are uncorrelated (fail to reject H0) p=0.672
data1: mean=23.667 stdv=7.314
data2: mean=86.833 stdv=67.264
covarience value :
[[  55.33333333  -49.85057471]
 [ -49.85057471 4680.41954023]]


Pearsons correlation: -0.098
Samples are uncorrelated (fail to reject H0) p=0.607
Spearmans correlation: -0.158
Samples are uncorrelated (fail to reject H0) p=0.406
Kendall correlation coefficient: -0.075
Samples are uncorrelated (fail to reject H0) p=0.567
data1: mean=71.560 stdv=8.149
data2: mean=9.040 stdv=5.459
covarience value :
[[69.17333333 -9.60666667]
 [-9.60666667 31.04      ]]


Pearsons correlation: -0.207
Samples are uncorrelated (fail to reject H0) p=0.320
Spearmans correlation: -0.311
Samples are uncorrelated (fail to reject H0) p=0.130
Kendall correlation coefficient: -0.219
Samples are uncorrelated (fail to reject H0) p=0.138
data1: mean=60.750 stdv=9.895
data2: mean=78.571 stdv=90.717
covarience value :
[[ 101.52777778   10.        ]
 [  10.         8534.32804233]]


Pearsons correlation: 0.011
Samples are uncorrelated (fail to reject H0) p=0.957
Spearmans correlation: -0.306
Samples are uncorrelated (fail to reject H0) p=0.113
Kendall correlation coefficient: -0.225
Samples are uncorrelated (fail to reject H0) p=0.099
data1: mean=76.429 stdv=2.251
data2: mean=24.321 stdv=26.650
covarience value :
[[  5.15844156  -9.59480519]
 [ -9.59480519 723.13116883]]


Pearsons correlation: -0.157
Samples are uncorrelated (fail to reject H0) p=0.248
Spearmans correlation: -0.269
Samples are correlated (reject H0) p=0.045
Kendall correlation coefficient: -0.194
Samples are correlated (reject H0) p=0.049
data1: mean=66.400 stdv=9.587
data2: mean=17.800 stdv=12.734
covarience value :
[[ 95.07586207 -20.26206897]
 [-20.26206897 167.75172414]]


Pearsons correlation: -0.160
Samples are uncorrelated (fail to reject H0) p=0.397
Spearmans correlation: -0.134
Samples are uncorrelated (fail to reject H0) p=0.479
Kendall correlation coefficient: -0.101
Samples are uncorrelated (fail to reject H0) p=0.442
data1: mean=75.133 stdv=11.865
data2: mean=34.033 stdv=15.913
covarience value :
[[145.63678161 -80.55632184]
 [-80.55632184 261.96436782]]


Pearsons correlation: -0.412
Samples are correlated (reject H0) p=0.024
Spearmans correlation: -0.378
Samples are correlated (reject H0) p=0.039
Kendall correlation coefficient: -0.263
Samples are correlated (reject H0) p=0.045
data1: mean=45.414 stdv=10.943
data2: mean=58.138 stdv=63.081
covarience value :
[[ 124.03694581  -68.3091133 ]
 [ -68.3091133  4121.26600985]]


Pearsons correlation: -0.096
Samples are uncorrelated (fail to reject H0) p=0.622
Spearmans correlation: -0.267
Samples are uncorrelated (fail to reject H0) p=0.161
Kendall correlation coefficient: -0.208
Samples are uncorrelated (fail to reject H0) p=0.118
data1: mean=58.465 stdv=13.725
data2: mean=3178.488 stdv=3237.654
covarience value :
[[1.92873754e+02 1.17662913e+04]
 [1.17662913e+04 1.07319821e+07]]


Pearsons correlation: 0.259
Samples are uncorrelated (fail to reject H0) p=0.094
Spearmans correlation: 0.201
Samples are uncorrelated (fail to reject H0) p=0.195
Kendall correlation coefficient: 0.192
Samples are uncorrelated (fail to reject H0) p=0.072
data1: mean=72.950 stdv=12.410
data2: mean=180.125 stdv=163.681
covarience value :
[[  157.94615385  -903.73717949]
 [ -903.73717949 27478.31730769]]


Pearsons correlation: -0.434
Samples are correlated (reject H0) p=0.005
Spearmans correlation: -0.389
Samples are correlated (reject H0) p=0.013
Kendall correlation coefficient: -0.240
Samples are correlated (reject H0) p=0.031
data1: mean=76.512 stdv=9.402
data2: mean=528.317 stdv=472.089
covarience value :
[[9.06060976e+01 6.55335366e+01]
 [6.55335366e+01 2.28440072e+05]]


Pearsons correlation: 0.014
Samples are uncorrelated (fail to reject H0) p=0.929
Spearmans correlation: 0.076
Samples are uncorrelated (fail to reject H0) p=0.635
Kendall correlation coefficient: 0.045
Samples are uncorrelated (fail to reject H0) p=0.685
data1: mean=60.688 stdv=7.095
data2: mean=7.562 stdv=7.494
covarience value :
[[51.41090426 -8.03324468]
 [-8.03324468 57.35771277]]


Pearsons correlation: -0.148
Samples are uncorrelated (fail to reject H0) p=0.316
Spearmans correlation: -0.117
Samples are uncorrelated (fail to reject H0) p=0.430
Kendall correlation coefficient: -0.106
Samples are uncorrelated (fail to reject H0) p=0.323
data1: mean=54.780 stdv=6.591
data2: mean=53.683 stdv=53.577
covarience value :
[[  44.52560976  111.12865854]
 [ 111.12865854 2942.22195122]]


Pearsons correlation: 0.307
Samples are uncorrelated (fail to reject H0) p=0.051
Spearmans correlation: 0.300
Samples are uncorrelated (fail to reject H0) p=0.057
Kendall correlation coefficient: 0.203
Samples are uncorrelated (fail to reject H0) p=0.071
data1: mean=77.273 stdv=2.199
data2: mean=4.773 stdv=7.914
covarience value :
[[ 5.06493506 -6.55411255]
 [-6.55411255 65.61255411]]


Pearsons correlation: -0.360
Samples are uncorrelated (fail to reject H0) p=0.100
Spearmans correlation: 0.118
Samples are uncorrelated (fail to reject H0) p=0.601
Kendall correlation coefficient: 0.090
Samples are uncorrelated (fail to reject H0) p=0.597
data1: mean=70.259 stdv=7.417
data2: mean=22.074 stdv=20.717
covarience value :
[[ 57.12250712  86.44159544]
 [ 86.44159544 445.68660969]]


Pearsons correlation: 0.542
Samples are correlated (reject H0) p=0.004
Spearmans correlation: 0.501
Samples are correlated (reject H0) p=0.008
Kendall correlation coefficient: 0.342
Samples are correlated (reject H0) p=0.014
data1: mean=58.800 stdv=9.495
data2: mean=1208.680 stdv=1157.404
covarience value :
[[9.39166667e+01 2.95530833e+03]
 [2.95530833e+03 1.39540039e+06]]


Pearsons correlation: 0.258
Samples are uncorrelated (fail to reject H0) p=0.213
Spearmans correlation: 0.262
Samples are uncorrelated (fail to reject H0) p=0.205
Kendall correlation coefficient: 0.187
Samples are uncorrelated (fail to reject H0) p=0.197
data1: mean=80.085 stdv=9.466
data2: mean=7793.830 stdv=10858.107
covarience value :
[[9.15578168e+01 3.31426887e+04]
 [3.31426887e+04 1.20461488e+08]]


Pearsons correlation: 0.316
Samples are correlated (reject H0) p=0.031
Spearmans correlation: 0.117
Samples are uncorrelated (fail to reject H0) p=0.434
Kendall correlation coefficient: 0.089
Samples are uncorrelated (fail to reject H0) p=0.387
data1: mean=62.000 stdv=14.573
data2: mean=59.955 stdv=54.568
covarience value :
[[ 222.47619048 -412.47619048]
 [-412.47619048 3119.47402597]]


Pearsons correlation: -0.495
Samples are correlated (reject H0) p=0.019
Spearmans correlation: -0.564
Samples are correlated (reject H0) p=0.006
Kendall correlation coefficient: -0.408
Samples are correlated (reject H0) p=0.009
data1: mean=50.700 stdv=10.765
data2: mean=69.067 stdv=89.582
covarience value :
[[ 119.87241379 -109.91034483]
 [-109.91034483 8301.71954023]]


Pearsons correlation: -0.110
Samples are uncorrelated (fail to reject H0) p=0.562
Spearmans correlation: -0.272
Samples are uncorrelated (fail to reject H0) p=0.146
Kendall correlation coefficient: -0.176
Samples are uncorrelated (fail to reject H0) p=0.180
data1: mean=80.767 stdv=10.354
data2: mean=1215.744 stdv=1607.258
covarience value :
[[1.09754153e+02 3.34022481e+03]
 [3.34022481e+03 2.64478634e+06]]


Pearsons correlation: 0.196
Samples are uncorrelated (fail to reject H0) p=0.208
Spearmans correlation: 0.089
Samples are uncorrelated (fail to reject H0) p=0.570
Kendall correlation coefficient: 0.062
Samples are uncorrelated (fail to reject H0) p=0.564
data1: mean=61.964 stdv=9.124
data2: mean=15.000 stdv=9.979
covarience value :
[[ 86.33201058 -15.33333333]
 [-15.33333333 103.25925926]]


Pearsons correlation: -0.162
Samples are uncorrelated (fail to reject H0) p=0.409
Spearmans correlation: -0.125
Samples are uncorrelated (fail to reject H0) p=0.527
Kendall correlation coefficient: -0.103
Samples are uncorrelated (fail to reject H0) p=0.451
data1: mean=45.182 stdv=11.159
data2: mean=20.773 stdv=26.483
covarience value :
[[130.44155844  30.9004329 ]
 [ 30.9004329  734.75541126]]


Pearsons correlation: 0.100
Samples are uncorrelated (fail to reject H0) p=0.659
Spearmans correlation: 0.110
Samples are uncorrelated (fail to reject H0) p=0.627
Kendall correlation coefficient: 0.076
Samples are uncorrelated (fail to reject H0) p=0.629
data1: mean=78.450 stdv=3.626
data2: mean=8.350 stdv=6.295
covarience value :
[[13.83947368 -7.42894737]
 [-7.42894737 41.71315789]]


Pearsons correlation: -0.309
Samples are uncorrelated (fail to reject H0) p=0.185
Spearmans correlation: -0.264
Samples are uncorrelated (fail to reject H0) p=0.261
Kendall correlation coefficient: -0.203
Samples are uncorrelated (fail to reject H0) p=0.251
data1: mean=74.892 stdv=7.752
data2: mean=6.568 stdv=4.722
covarience value :
[[61.76576577  5.25750751]
 [ 5.25750751 22.91891892]]


Pearsons correlation: 0.140
Samples are uncorrelated (fail to reject H0) p=0.409
Spearmans correlation: 0.108
Samples are uncorrelated (fail to reject H0) p=0.524
Kendall correlation coefficient: 0.084
Samples are uncorrelated (fail to reject H0) p=0.484
data1: mean=80.179 stdv=8.540
data2: mean=9.071 stdv=8.771
covarience value :
[[ 75.63359788 -14.05026455]
 [-14.05026455  79.77248677]]


Pearsons correlation: -0.181
Samples are uncorrelated (fail to reject H0) p=0.357
Spearmans correlation: -0.236
Samples are uncorrelated (fail to reject H0) p=0.227
Kendall correlation coefficient: -0.176
Samples are uncorrelated (fail to reject H0) p=0.213


Empty DataFrame
Columns: []
Index: []

# Making dataframe for findings

In [14]:
dframe = pd.DataFrame({'Country name':countrys, 'Pearson\'s correlation':correlationp, 'P-value of pearson\'s correlation': pearp, 'Comment on pearson\'s correlation':commentpearson,'Spearsman\'s correlation':correlations,'P-value of spearman\'s correlation':spearp, 'Comment on spearsman\'s correlation':commentspearsman, 'Kendall\'s correlation':correlationk,'P-value of kendall\'s correlation':kendallp, 'Comment on kendall\'s correlation':commentkendall})
dframe

Country name Pearson's correlation  \
0           Afghanistan                -0.209   
1               Albania                -0.321   
2               Algeria                 0.366   
3               Andorra                 0.517   
4             Argentina                 0.347   
..                  ...                   ...   
110             Uruguay                -0.162   
111          Uzbekistan                 0.100   
112           Venezuela                -0.309   
113             Vietnam                 0.140   
114  West Bank and Gaza                -0.181   

    P-value of pearson's correlation Comment on pearson's correlation  \
0                              0.338                     uncorrelated   
1                              0.090                     uncorrelated   
2                              0.036                       correlated   
3                              0.014                       correlated   
4                              0.070                     uncorrelated   
..                               ...                              ...   
110                            0.409                     uncorrelated   
111                            0.659                     uncorrelated   
112                            0.185                     uncorrelated   
113                            0.409                     uncorrelated   
114                            0.357                     uncorrelated   

    Spearsman's correlation P-value of spearman's correlation  \
0                    -0.210                             0.337   
1                    -0.305                             0.107   
2                     0.343                             0.051   
3                     0.498                             0.018   
4                     0.519                             0.005   
..                      ...                               ...   
110                  -0.125                             0.527   
111                   0.110                             0.627   
112                  -0.264                             0.261   
113                   0.108                             0.524   
114                  -0.236                             0.227   

    Comment on spearsman's correlation Kendall's correlation  \
0                         uncorrelated                -0.139   
1                         uncorrelated                -0.243   
2                         uncorrelated                 0.189   
3                           correlated                 0.359   
4                           correlated                 0.401   
..                                 ...                   ...   
110                       uncorrelated                -0.103   
111                       uncorrelated                 0.076   
112                       uncorrelated                -0.203   
113                       uncorrelated                 0.084   
114                       uncorrelated                -0.176   

    P-value of kendall's correlation Comment on kendall's correlation  
0                              0.366                     uncorrelated  
1                              0.071                     uncorrelated  
2                              0.128                     uncorrelated  
3                              0.022                       correlated  
4                              0.003                       correlated  
..                               ...                              ...  
110                            0.451                     uncorrelated  
111                            0.629                     uncorrelated  
112                            0.251                     uncorrelated  
113                            0.484                     uncorrelated  
114                            0.213                     uncorrelated  

[115 rows x 10 columns]

#  Making csv for findings

In [15]:
dframe.to_csv(r'humidityrelatonfindings.csv', index=False)

In [4]:
correlations.sort()
correlationk.sort()
correlationp.sort()

In [5]:
print(correlationp)

['-0.0093', '-0.0311', '-0.0504', '-0.0604', '-0.0834', '-0.0865', '-0.0955', '-0.0980', '-0.1044', '-0.1053', '-0.1102', '-0.1247', '-0.1479', '-0.1527', '-0.1571', '-0.1604', '-0.1624', '-0.1627', '-0.1710', '-0.1752', '-0.1764', '-0.1809', '-0.1918', '-0.1957', '-0.2003', '-0.2073', '-0.2091', '-0.2116', '-0.2123', '-0.2171', '-0.2310', '-0.2318', '-0.2357', '-0.2803', '-0.2818', '-0.2831', '-0.2993', '-0.3092', '-0.3209', '-0.3360', '-0.3375', '-0.3377', '-0.3468', '-0.3493', '-0.3566', '-0.3595', '-0.3740', '-0.3822', '-0.3936', '-0.3961', '-0.3973', '-0.4124', '-0.4135', '-0.4253', '-0.4338', '-0.4663', '-0.4897', '-0.4951', '-0.5477', '-0.5565', '-0.5902', '-0.6352', '-0.6586', '-0.6587', '-0.6931', '-0.7123', '-0.7438', '-0.7931', '0.0022', '0.0107', '0.0144', '0.0159', '0.0169', '0.0181', '0.0197', '0.0198', '0.0454', '0.0792', '0.0985', '0.0998', '0.1118', '0.1186', '0.1209', '0.1263', '0.1315', '0.1397', '0.1538', '0.1591', '0.1921', '0.1957', '0.1961', '0.2016', '0.2269', '

In [6]:
print(correlations)

['-0.0098', '-0.0182', '-0.0330', '-0.0456', '-0.0711', '-0.0874', '-0.0915', '-0.0980', '-0.1021', '-0.1066', '-0.1166', '-0.1183', '-0.1248', '-0.1249', '-0.1328', '-0.1343', '-0.1415', '-0.1474', '-0.1576', '-0.1682', '-0.2057', '-0.2098', '-0.2217', '-0.2297', '-0.2361', '-0.2638', '-0.2674', '-0.2687', '-0.2688', '-0.2720', '-0.2759', '-0.2803', '-0.2829', '-0.2924', '-0.3029', '-0.3052', '-0.3064', '-0.3112', '-0.3125', '-0.3143', '-0.3269', '-0.3284', '-0.3333', '-0.3344', '-0.3469', '-0.3665', '-0.3676', '-0.3684', '-0.3785', '-0.3894', '-0.3907', '-0.3932', '-0.4058', '-0.4194', '-0.4301', '-0.4310', '-0.4350', '-0.4366', '-0.4652', '-0.5513', '-0.5547', '-0.5639', '-0.5799', '-0.6102', '-0.6403', '-0.7237', '-0.7436', '-0.8398', '0.0013', '0.0154', '0.0228', '0.0483', '0.0556', '0.0655', '0.0700', '0.0764', '0.0828', '0.0842', '0.0892', '0.0899', '0.0986', '0.1081', '0.1098', '0.1169', '0.1180', '0.1261', '0.1265', '0.1266', '0.1272', '0.1638', '0.1889', '0.2014', '0.2027', '

In [7]:
print(correlationk)

['-0.0018', '-0.0105', '-0.0132', '-0.0174', '-0.0323', '-0.0514', '-0.0539', '-0.0550', '-0.0622', '-0.0752', '-0.0805', '-0.0877', '-0.0934', '-0.1009', '-0.1030', '-0.1058', '-0.1121', '-0.1174', '-0.1189', '-0.1195', '-0.1209', '-0.1364', '-0.1391', '-0.1460', '-0.1504', '-0.1685', '-0.1756', '-0.1762', '-0.1936', '-0.1973', '-0.1973', '-0.1979', '-0.1994', '-0.1995', '-0.2030', '-0.2083', '-0.2188', '-0.2227', '-0.2253', '-0.2325', '-0.2365', '-0.2385', '-0.2398', '-0.2430', '-0.2431', '-0.2539', '-0.2605', '-0.2626', '-0.2628', '-0.2630', '-0.2643', '-0.2677', '-0.2733', '-0.2775', '-0.2851', '-0.2890', '-0.3149', '-0.3155', '-0.3214', '-0.3232', '-0.3714', '-0.4079', '-0.4120', '-0.4240', '-0.4277', '-0.4298', '-0.5347', '-0.5717', '-0.6587', '0.0016', '0.0144', '0.0147', '0.0208', '0.0245', '0.0438', '0.0446', '0.0556', '0.0621', '0.0646', '0.0659', '0.0664', '0.0761', '0.0810', '0.0832', '0.0843', '0.0892', '0.0893', '0.0905', '0.0982', '0.1214', '0.1233', '0.1286', '0.1511', 

In [8]:
statistics.median(correlationp)

'-0.4951'

In [9]:
statistics.median(correlations)

'-0.4366'

In [10]:
statistics.median(correlationk)

'-0.3155'