# Imported important modules

In [17]:
from numpy import mean
from numpy import std
from numpy.random import randn
from numpy.random import seed
from matplotlib import pyplot
import pandas as pd
from numpy import cov
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import kendalltau
import numpy as np
import math
import plotly.graph_objects as go
import plotly.express as px
import requests
import json
from flask import jsonify
from csv import writer
import csv
from statistics import mean
import statistics

# Making csv file

In [ ]:



url = 'http://coronavirus-tracker-api.herokuapp.com/all'
url_iso2 = 'https://restcountries.eu/rest/v2/'


response_iso2 = requests.get(url_iso2)
lst_iso2 = json.loads(response_iso2.text)

response = requests.get(url)
lst = json.loads(response.text)

dict_pop = {}
dict_iso3 = {}
dict_affected = {}
dict_deaths = {}
dict_recovered = {}

for i in lst_iso2:
    dict_pop[i['alpha2Code']] = i['population']
    dict_iso3[i['alpha2Code']] = i['alpha3Code']
    dict_affected[i['alpha2Code']] = {}
    dict_deaths[i['alpha2Code']] = {}
    dict_recovered[i['alpha2Code']] = {}
      

## INITIALIZATION ##

for i in lst['confirmed']['locations']:
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_affected[code][j] = 0

for i in lst['recovered']['locations']:
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_recovered[code][j] = 0

for i in lst['deaths']['locations']:
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_deaths[code][j] = 0         


## Summing up ##

for i in lst['deaths']['locations']:
    name = i['country']
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_deaths[code][j] = dict_deaths[code][j] + i['history'][j] 

for i in lst['recovered']['locations']:
    name = i['country']
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_recovered[code][j] = dict_recovered[code][j] + i['history'][j] 

for i in lst['confirmed']['locations']:
    name = i['country']
    code = i['country_code']
    if code in dict_iso3:
        for j in i['history']:
            dict_affected[code][j] = dict_affected[code][j] + i['history'][j]                         

#************************************************
# with open('Literacy_rate/Databihin.csv', 'rt') as f:
#     lines = csv.reader(f)
#     for line in lines:
#         map_iso3_latest_year[line[0]] = 2018
#         map_iso3_literacy[line[0]] = 99
#         # print(line[0], map_iso3_literacy[line[0]])
#************************************************
map_country_dataList_mx_temp = {}
map_country_dataList_mn_temp = {}
map_country_dataList_hum = {}
with open('weather_data_countries_covid19.csv') as f:
    lines = csv.reader(f)
    for line in lines:
        if line[1] == 'maxtempC':
            map_country_dataList_mx_temp[line[0]] = line[2:-1]
        elif line[1] == 'mintempC':
            map_country_dataList_mn_temp[line[0]] = line[2:-1]
        else:
            map_country_dataList_hum[line[0]] = line[2:-1]

# for i in map_country_dataList_mx_temp:
#     print(i, map_country_dataList_mx_temp[i])

with open('country_model_e.csv', 'w') as csv_file:
    csv_writer = csv.writer(csv_file)
    headers = ['Country_name', 'Country_code_iso2', 'Country_code_iso3', 'Date', 'Tot_affected', 'Tot_dead', 'Tot_recov', 'Population', 'minTempC', 'maxTempC', 'Humidity', 'newlyAffected','newlyDead','newlyRecovered']
    csv_writer.writerow(headers)
    for i in lst['confirmed']['locations']:
        name = i['country']
        code = i['country_code']
        if code in dict_iso3:
            vnt = 0
            prev = 0
            prev_d = 0
            prev_r = 0
            for j in i['history']:
                date = j + '20'
                if name in map_country_dataList_mn_temp:
                    #entry = [name, code, dict_iso3[code], date, dict_affected[code][j], dict_deaths[code][j], dict_recovered[code][j], dict_pop[code], map_country_dataList_mn_temp[name][vnt], map_country_dataList_mx_temp[name][vnt], map_country_dataList_hum[name][vnt], dict_affected[code][j]]

                    try:
                        mn_temp = map_country_dataList_mn_temp[name][vnt]
                        mx_temp = map_country_dataList_mx_temp[name][vnt]
                        hum = map_country_dataList_hum[name][vnt]
                    except:
                        mn_temp = 'null'
                        mx_temp = 'null'
                        hum = 'null'

                    try:
                        newly_aff = dict_affected[code][j] - prev
                        newly_rec = dict_recovered[code][j] - prev_r
                        newly_ded = dict_deaths[code][j] - prev_d
                    except:
                        newly_aff = dict_affected[code][j]
                        newly_rec = dict_recovered[code][j]
                        newly_ded = dict_deaths[code][j]
                    prev = dict_affected[code][j]
                    prev_r = dict_recovered[code][j]
                    prev_d = dict_deaths[code][j]
                    #newly_aff = dict_affected[code][j] - dict_affected[code][j-1]
                    ent = [name, code, dict_iso3[code], date, dict_affected[code].get(j, 0), dict_deaths[code].get(j, 0), dict_recovered[code].get(j, 0), dict_pop[code], mn_temp, mx_temp, hum, newly_aff, newly_ded, newly_rec]
                vnt = vnt + 1
                # if vnt > 60:
                #     break
                csv_writer.writerow(ent)
                if date == '4/6/2020':
                    break
    




# two variables for plotting

# my written function for pearson (  no need because scipy has built in function)

In [ ]:
def average(x):
    assert len(x) > 0
    return float(sum(x)) / len(x)

def pearson_def(x, y):
    assert len(x) == len(y)
    n = len(x)
    assert n > 0
    avg_x = average(x)
    avg_y = average(y)
    diffprod = 0
    xdiff2 = 0
    ydiff2 = 0
    for idx in range(n):
        xdiff = x[idx] - avg_x
        ydiff = y[idx] - avg_y
        diffprod += xdiff * ydiff
        xdiff2 += xdiff * xdiff
        ydiff2 += ydiff * ydiff

    return diffprod / math.sqrt(xdiff2 * ydiff2)

# A function for checking different times of correlations, mean, standard deviation and covariance

In [24]:
countrys = [] #country names
correlationp = [] ##pearson
correlations = [] #spearsman
correlationk = [] #kendall
commentpearson =[]
commentspearsman = []
commentkendall = []
mediantemp = []
mediannewlyaffected = []
pearp=[]
spearp=[]
kendallp=[]

def correl(bd):
    Bd1 = bd.iloc[:,9:10]
    Bd2 = bd.iloc[:,11:12]
    countrys.append(bd.iloc[0,0])
    
    X = [x[0] for x in Bd1.values.tolist()]  #list comprehension
    Y = [y[0] for y in Bd2.values.tolist()]
    print('data1: mean=%.3f stdv=%.3f' % (mean(X), std(X)))
    print('data2: mean=%.3f stdv=%.3f' % (mean(Y), std(Y)))
    
    mediantemp.append(statistics.median(X)) 
    mediannewlyaffected.append(statistics.median(Y)) 

    
    #print('my function pearson : %.5f' % pearson_def(X,Y))
    
    covariance = cov(X,Y)
    print('covarience value :')
    print( covariance)
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=X,y=Y,mode='markers',marker_color=Y)) # hover text goes here

    fig.update_layout(title='Temperature vs Affected', xaxis=dict(title='Temperature'),yaxis=dict(title='Total # of Affected'))
    
    fig.show()
    ##pyplot.scatter(Bd1, Bd2)
    #pyplot.xlabel("temparature")
    #pyplot.ylabel("Total Affected")
    #pyplot.show()
    alpha = 0.05 #setting my significant level 5 %
    corr, r = pearsonr(X,Y)
    print('Pearsons correlation: %.3f' % corr)
    correlationp.append('%.3f'%(corr))
    
    if r > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % r)
        commentpearson.append('uncorrelated')
        pearp.append('%.3f'%(r))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % r)
        commentpearson.append('correlated')
        pearp.append('%.3f'%(r))
        
    corr, p = spearmanr(X,Y)
    print('Spearmans correlation: %.3f' % corr)
    correlations.append('%.3f'%(corr))
    
    # interpret the significance
    
    if p > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % p)
        commentspearsman.append('uncorrelated')
        spearp.append('%.3f'%(p))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % p)
        commentspearsman.append('correlated')
        spearp.append('%.3f'%(p))
        
    
    coef, q = kendalltau(X,Y)
    print('Kendall correlation coefficient: %.3f' % coef)
    correlationk.append('%.3f'%(coef))
    # interpret the significance
    alpha = 0.05
    if q > alpha:
        print('Samples are uncorrelated (fail to reject H0) p=%.3f' % q)
        commentkendall.append('uncorrelated')
        kendallp.append('%.3f'%(q))
    else:
        print('Samples are correlated (reject H0) p=%.3f' % q)
        commentkendall.append('correlated')
        kendallp.append('%.3f'%(q))

    


# For all countries (New approach)


# Deleting duplicates

In [ ]:
#deleting duplicates
with open('country_model_e.csv','r') as in_file, open('temperaturehumidity.csv','w') as out_file:
    seen = set() # set for fast O(1) amortized lookup
    for line in in_file:
        if line in seen: continue # skip duplicate

        seen.add(line)
        out_file.write(line)

# Temaparaturehumidity has temperature and humidity of 5 days prior to covid data (covid data from 27/1/2020 to 6/4/2020) And did some cleaning (new cases 0 are removed)

In [2]:
with open('temperaturehumidity.csv', "r") as f:
    data = list(csv.reader(f))

with open('temperaturehumidity2.csv', "w") as f2:
    writer = csv.writer(f2)
    for row in data:
        if row: # only use non-empty lines (or use if len(row)>2)
            if row[8] != 'null' and row[9] != 'null' and row[10] != 'null' and row[11]!= '0':
                  writer.writerow(row)

# Preparing datasets and calling functions to find out correlations

In [25]:
df = pd.read_csv('temperaturehumidity2.csv')
dfg = df.groupby('Country_name').apply(correl)
dfg.head(20)
        
#print(dfg.size())
#for i in dfg.size():
   # print(i)
#for name, group in dfg:
    #print(name)
    #print(group)
    #print(group.size())
    #for i in range(0,13376,76):
        #df1 = df.iloc[i:i+71, 9:10]
        #df2 = df.iloc[i+5:i+76, 11:12]
        #print(df1)
        #print('the index no. is : %s' %i )
        #correl(df1,df2)
        #countrys.append(df.iloc[i,0])

#X = df.iloc[0:71, 8:9]
#Y = df.iloc[0:71, 4:5]
#Z = df.iloc[71:142, 8:9]"""

data1: mean=11.870 stdv=3.757
data2: mean=15.957 stdv=17.682
covarience value :
[[ 14.75494071  27.9486166 ]
 [ 27.9486166  326.86166008]]


Pearsons correlation: 0.402
Samples are uncorrelated (fail to reject H0) p=0.057
Spearmans correlation: 0.540
Samples are correlated (reject H0) p=0.008
Kendall correlation coefficient: 0.412
Samples are correlated (reject H0) p=0.009
data1: mean=14.724 stdv=3.628
data2: mean=13.000 stdv=8.120
covarience value :
[[13.63546798  7.46428571]
 [ 7.46428571 68.28571429]]


Pearsons correlation: 0.245
Samples are uncorrelated (fail to reject H0) p=0.201
Spearmans correlation: 0.389
Samples are correlated (reject H0) p=0.037
Kendall correlation coefficient: 0.272
Samples are correlated (reject H0) p=0.047
data1: mean=18.848 stdv=3.258
data2: mean=43.121 stdv=47.868
covarience value :
[[  10.94507576  -18.32481061]
 [ -18.32481061 2362.92234848]]


Pearsons correlation: -0.114
Samples are uncorrelated (fail to reject H0) p=0.528
Spearmans correlation: -0.142
Samples are uncorrelated (fail to reject H0) p=0.430
Kendall correlation coefficient: -0.090
Samples are uncorrelated (fail to reject H0) p=0.482
data1: mean=7.909 stdv=4.776
data2: mean=23.864 stdv=12.392
covarience value :
[[ 23.8961039   -3.39393939]
 [ -3.39393939 160.88528139]]


Pearsons correlation: -0.055
Samples are uncorrelated (fail to reject H0) p=0.809
Spearmans correlation: -0.058
Samples are uncorrelated (fail to reject H0) p=0.798
Kendall correlation coefficient: -0.041
Samples are uncorrelated (fail to reject H0) p=0.798
data1: mean=32.107 stdv=4.047
data2: mean=55.500 stdv=59.832
covarience value :
[[  16.98809524  -70.72222222]
 [ -70.72222222 3712.48148148]]


Pearsons correlation: -0.282
Samples are uncorrelated (fail to reject H0) p=0.147
Spearmans correlation: -0.304
Samples are uncorrelated (fail to reject H0) p=0.116
Kendall correlation coefficient: -0.217
Samples are uncorrelated (fail to reject H0) p=0.116
data1: mean=14.214 stdv=3.395
data2: mean=29.893 stdv=23.542
covarience value :
[[ 11.95238095  15.39417989]
 [ 15.39417989 574.76587302]]


Pearsons correlation: 0.186
Samples are uncorrelated (fail to reject H0) p=0.344
Spearmans correlation: 0.230
Samples are uncorrelated (fail to reject H0) p=0.240
Kendall correlation coefficient: 0.183
Samples are uncorrelated (fail to reject H0) p=0.188
data1: mean=23.683 stdv=4.370
data2: mean=141.171 stdv=151.460
covarience value :
[[ 1.95719512e+01 -2.15819512e+02]
 [-2.15819512e+02  2.35136451e+04]]


Pearsons correlation: -0.318
Samples are correlated (reject H0) p=0.043
Spearmans correlation: -0.483
Samples are correlated (reject H0) p=0.001
Kendall correlation coefficient: -0.332
Samples are correlated (reject H0) p=0.003
data1: mean=10.750 stdv=3.819
data2: mean=307.425 stdv=312.857
covarience value :
[[1.49615385e+01 4.50955128e+02]
 [4.50955128e+02 1.00389020e+05]]


Pearsons correlation: 0.368
Samples are correlated (reject H0) p=0.019
Spearmans correlation: 0.279
Samples are uncorrelated (fail to reject H0) p=0.081
Kendall correlation coefficient: 0.183
Samples are uncorrelated (fail to reject H0) p=0.108
data1: mean=12.160 stdv=3.068
data2: mean=25.640 stdv=23.215
covarience value :
[[  9.80666667   6.14333333]
 [  6.14333333 561.40666667]]


Pearsons correlation: 0.083
Samples are uncorrelated (fail to reject H0) p=0.694
Spearmans correlation: 0.102
Samples are uncorrelated (fail to reject H0) p=0.628
Kendall correlation coefficient: 0.087
Samples are uncorrelated (fail to reject H0) p=0.556
data1: mean=22.243 stdv=2.198
data2: mean=20.432 stdv=19.631
covarience value :
[[  4.96696697   7.003003  ]
 [  7.003003   396.08558559]]


Pearsons correlation: 0.158
Samples are uncorrelated (fail to reject H0) p=0.351
Spearmans correlation: 0.152
Samples are uncorrelated (fail to reject H0) p=0.369
Kendall correlation coefficient: 0.124
Samples are uncorrelated (fail to reject H0) p=0.312
data1: mean=33.381 stdv=3.273
data2: mean=5.857 stdv=7.415
covarience value :
[[11.24761905 15.90714286]
 [15.90714286 57.72857143]]


Pearsons correlation: 0.624
Samples are correlated (reject H0) p=0.002
Spearmans correlation: 0.534
Samples are correlated (reject H0) p=0.013
Kendall correlation coefficient: 0.460
Samples are correlated (reject H0) p=0.007
data1: mean=6.105 stdv=2.751
data2: mean=36.842 stdv=47.404
covarience value :
[[   7.98830409   25.29532164]
 [  25.29532164 2372.02923977]]


Pearsons correlation: 0.184
Samples are uncorrelated (fail to reject H0) p=0.451
Spearmans correlation: 0.280
Samples are uncorrelated (fail to reject H0) p=0.245
Kendall correlation coefficient: 0.236
Samples are uncorrelated (fail to reject H0) p=0.177
data1: mean=10.054 stdv=2.721
data2: mean=562.541 stdv=576.748
covarience value :
[[7.60810811e+00 9.71247748e+02]
 [9.71247748e+02 3.41878755e+05]]


Pearsons correlation: 0.602
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.581
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.450
Samples are correlated (reject H0) p=0.000
data1: mean=13.000 stdv=1.180
data2: mean=7.957 stdv=6.423
covarience value :
[[ 1.45454545  0.5       ]
 [ 0.5        43.13438735]]


Pearsons correlation: 0.063
Samples are uncorrelated (fail to reject H0) p=0.775
Spearmans correlation: 0.058
Samples are uncorrelated (fail to reject H0) p=0.793
Kendall correlation coefficient: 0.041
Samples are uncorrelated (fail to reject H0) p=0.803
data1: mean=8.500 stdv=5.494
data2: mean=22.467 stdv=20.638
covarience value :
[[ 31.22413793   9.06896552]
 [  9.06896552 440.60229885]]


Pearsons correlation: 0.077
Samples are uncorrelated (fail to reject H0) p=0.685
Spearmans correlation: 0.079
Samples are uncorrelated (fail to reject H0) p=0.680
Kendall correlation coefficient: 0.060
Samples are uncorrelated (fail to reject H0) p=0.653
data1: mean=26.152 stdv=1.305
data2: mean=368.515 stdv=409.466
covarience value :
[[ 1.75757576e+00 -2.42080492e+02]
 [-2.42080492e+02  1.72902195e+05]]


Pearsons correlation: -0.439
Samples are correlated (reject H0) p=0.011
Spearmans correlation: -0.304
Samples are uncorrelated (fail to reject H0) p=0.085
Kendall correlation coefficient: -0.212
Samples are uncorrelated (fail to reject H0) p=0.113
data1: mean=29.520 stdv=1.136
data2: mean=5.400 stdv=5.418
covarience value :
[[ 1.34333333 -1.59166667]
 [-1.59166667 30.58333333]]


Pearsons correlation: -0.248
Samples are uncorrelated (fail to reject H0) p=0.231
Spearmans correlation: -0.191
Samples are uncorrelated (fail to reject H0) p=0.362
Kendall correlation coefficient: -0.141
Samples are uncorrelated (fail to reject H0) p=0.386
data1: mean=10.185 stdv=5.423
data2: mean=20.333 stdv=10.805
covarience value :
[[ 30.54131054  -4.75641026]
 [ -4.75641026 121.23076923]]


Pearsons correlation: -0.078
Samples are uncorrelated (fail to reject H0) p=0.698
Spearmans correlation: -0.174
Samples are uncorrelated (fail to reject H0) p=0.385
Kendall correlation coefficient: -0.129
Samples are uncorrelated (fail to reject H0) p=0.357
data1: mean=40.292 stdv=1.719
data2: mean=15.167 stdv=9.095
covarience value :
[[ 3.08514493 -0.0942029 ]
 [-0.0942029  86.31884058]]


Pearsons correlation: -0.006
Samples are uncorrelated (fail to reject H0) p=0.979
Spearmans correlation: -0.083
Samples are uncorrelated (fail to reject H0) p=0.701
Kendall correlation coefficient: -0.065
Samples are uncorrelated (fail to reject H0) p=0.681
data1: mean=20.833 stdv=0.687
data2: mean=1.167 stdv=0.373
covarience value :
[[0.56666667 0.03333333]
 [0.03333333 0.16666667]]


Pearsons correlation: 0.108
Samples are uncorrelated (fail to reject H0) p=0.838
Spearmans correlation: 0.141
Samples are uncorrelated (fail to reject H0) p=0.789
Kendall correlation coefficient: 0.135
Samples are uncorrelated (fail to reject H0) p=0.752
data1: mean=37.526 stdv=1.045
data2: mean=5.947 stdv=8.256
covarience value :
[[ 1.15204678  2.75146199]
 [ 2.75146199 71.94152047]]


Pearsons correlation: 0.302
Samples are uncorrelated (fail to reject H0) p=0.209
Spearmans correlation: 0.505
Samples are correlated (reject H0) p=0.027
Kendall correlation coefficient: 0.401
Samples are correlated (reject H0) p=0.037
data1: mean=-0.413 stdv=5.799
data2: mean=359.978 stdv=557.055
covarience value :
[[3.43811594e+01 1.50665749e+03]
 [1.50665749e+03 3.17206200e+05]]


Pearsons correlation: 0.456
Samples are correlated (reject H0) p=0.001
Spearmans correlation: 0.505
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.347
Samples are correlated (reject H0) p=0.001
data1: mean=24.794 stdv=2.246
data2: mean=202.647 stdv=172.047
covarience value :
[[ 5.19875223e+00 -1.24620321e+02]
 [-1.24620321e+02  3.04970232e+04]]


Pearsons correlation: -0.313
Samples are uncorrelated (fail to reject H0) p=0.072
Spearmans correlation: -0.383
Samples are correlated (reject H0) p=0.025
Kendall correlation coefficient: -0.268
Samples are correlated (reject H0) p=0.035
data1: mean=10.803 stdv=6.465
data2: mean=1103.985 stdv=2221.642
covarience value :
[[ 4.24375291e+01 -5.93520303e+03]
 [-5.93520303e+03  5.01162694e+06]]


Pearsons correlation: -0.407
Samples are correlated (reject H0) p=0.001
Spearmans correlation: -0.611
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.410
Samples are correlated (reject H0) p=0.000
data1: mean=20.821 stdv=1.605
data2: mean=56.393 stdv=45.231
covarience value :
[[   2.67063492  -49.63095238]
 [ -49.63095238 2121.58068783]]


Pearsons correlation: -0.659
Samples are correlated (reject H0) p=0.000
Spearmans correlation: -0.691
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: -0.524
Samples are correlated (reject H0) p=0.000
data1: mean=32.833 stdv=2.267
data2: mean=7.500 stdv=8.480
covarience value :
[[ 6.16666667  0.5       ]
 [ 0.5        86.3       ]]


Pearsons correlation: 0.022
Samples are uncorrelated (fail to reject H0) p=0.967
Spearmans correlation: 0.044
Samples are uncorrelated (fail to reject H0) p=0.934
Kendall correlation coefficient: 0.071
Samples are uncorrelated (fail to reject H0) p=0.846
data1: mean=31.737 stdv=2.489
data2: mean=8.474 stdv=6.885
covarience value :
[[ 6.53801170e+00 -3.50877193e-02]
 [-3.50877193e-02  5.00409357e+01]]


Pearsons correlation: -0.002
Samples are uncorrelated (fail to reject H0) p=0.994
Spearmans correlation: -0.001
Samples are uncorrelated (fail to reject H0) p=0.997
Kendall correlation coefficient: 0.006
Samples are uncorrelated (fail to reject H0) p=0.971
data1: mean=28.633 stdv=1.643
data2: mean=15.567 stdv=9.608
covarience value :
[[ 2.79195402 -0.88850575]
 [-0.88850575 95.4954023 ]]


Pearsons correlation: -0.054
Samples are uncorrelated (fail to reject H0) p=0.775
Spearmans correlation: -0.088
Samples are uncorrelated (fail to reject H0) p=0.644
Kendall correlation coefficient: -0.028
Samples are uncorrelated (fail to reject H0) p=0.841
data1: mean=35.211 stdv=3.105
data2: mean=17.000 stdv=19.309
covarience value :
[[ 10.1754386    5.22222222]
 [  5.22222222 393.55555556]]


Pearsons correlation: 0.083
Samples are uncorrelated (fail to reject H0) p=0.737
Spearmans correlation: -0.103
Samples are uncorrelated (fail to reject H0) p=0.675
Kendall correlation coefficient: -0.101
Samples are uncorrelated (fail to reject H0) p=0.568
data1: mean=12.194 stdv=4.274
data2: mean=33.944 stdv=31.089
covarience value :
[[ 18.78968254  25.12539683]
 [ 25.12539683 994.11111111]]


Pearsons correlation: 0.184
Samples are uncorrelated (fail to reject H0) p=0.283
Spearmans correlation: 0.242
Samples are uncorrelated (fail to reject H0) p=0.156
Kendall correlation coefficient: 0.184
Samples are uncorrelated (fail to reject H0) p=0.133
data1: mean=29.261 stdv=2.557
data2: mean=15.217 stdv=11.843
covarience value :
[[  6.83794466  21.84980237]
 [ 21.84980237 146.63241107]]


Pearsons correlation: 0.690
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.802
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.653
Samples are correlated (reject H0) p=0.000
data1: mean=17.462 stdv=2.872
data2: mean=17.885 stdv=13.305
covarience value :
[[  8.57846154  -8.34461538]
 [ -8.34461538 184.10615385]]


Pearsons correlation: -0.210
Samples are uncorrelated (fail to reject H0) p=0.303
Spearmans correlation: -0.217
Samples are uncorrelated (fail to reject H0) p=0.287
Kendall correlation coefficient: -0.135
Samples are uncorrelated (fail to reject H0) p=0.359
data1: mean=6.250 stdv=1.498
data2: mean=135.417 stdv=104.070
covarience value :
[[ 2.30714286e+00 -1.70500000e+01]
 [-1.70500000e+01  1.11399643e+04]]


Pearsons correlation: -0.106
Samples are uncorrelated (fail to reject H0) p=0.537
Spearmans correlation: -0.082
Samples are uncorrelated (fail to reject H0) p=0.636
Kendall correlation coefficient: -0.026
Samples are uncorrelated (fail to reject H0) p=0.834
data1: mean=27.826 stdv=1.049
data2: mean=79.478 stdv=67.532
covarience value :
[[1.15019763e+00 7.40513834e+00]
 [7.40513834e+00 4.76780632e+03]]


Pearsons correlation: 0.100
Samples are uncorrelated (fail to reject H0) p=0.650
Spearmans correlation: -0.004
Samples are uncorrelated (fail to reject H0) p=0.987
Kendall correlation coefficient: 0.000
Samples are uncorrelated (fail to reject H0) p=1.000
data1: mean=18.900 stdv=0.907
data2: mean=124.900 stdv=126.702
covarience value :
[[ 8.51724138e-01 -9.97586207e+00]
 [-9.97586207e+00  1.66068517e+04]]


Pearsons correlation: -0.084
Samples are uncorrelated (fail to reject H0) p=0.659
Spearmans correlation: -0.207
Samples are uncorrelated (fail to reject H0) p=0.271
Kendall correlation coefficient: -0.161
Samples are uncorrelated (fail to reject H0) p=0.265
data1: mean=23.455 stdv=3.924
data2: mean=40.061 stdv=35.728
covarience value :
[[  15.88068182   52.75284091]
 [  52.75284091 1316.37121212]]


Pearsons correlation: 0.365
Samples are correlated (reject H0) p=0.037
Spearmans correlation: 0.264
Samples are uncorrelated (fail to reject H0) p=0.137
Kendall correlation coefficient: 0.168
Samples are uncorrelated (fail to reject H0) p=0.189
data1: mean=4.290 stdv=2.003
data2: mean=35.742 stdv=31.173
covarience value :
[[   4.14623656   12.57741935]
 [  12.57741935 1004.1311828 ]]


Pearsons correlation: 0.195
Samples are uncorrelated (fail to reject H0) p=0.293
Spearmans correlation: 0.134
Samples are uncorrelated (fail to reject H0) p=0.473
Kendall correlation coefficient: 0.081
Samples are uncorrelated (fail to reject H0) p=0.545
data1: mean=3.250 stdv=1.801
data2: mean=60.500 stdv=60.686
covarience value :
[[3.33571429e+00 5.51000000e+01]
 [5.51000000e+01 3.78802857e+03]]


Pearsons correlation: 0.490
Samples are correlated (reject H0) p=0.002
Spearmans correlation: 0.422
Samples are correlated (reject H0) p=0.010
Kendall correlation coefficient: 0.324
Samples are correlated (reject H0) p=0.009
data1: mean=11.773 stdv=2.770
data2: mean=1712.227 stdv=1889.974
covarience value :
[[7.85412262e+00 1.90900634e+03]
 [1.90900634e+03 3.65506962e+06]]


Pearsons correlation: 0.356
Samples are correlated (reject H0) p=0.018
Spearmans correlation: 0.356
Samples are correlated (reject H0) p=0.018
Kendall correlation coefficient: 0.249
Samples are correlated (reject H0) p=0.023
data1: mean=14.033 stdv=4.637
data2: mean=6.267 stdv=4.892
covarience value :
[[22.24022989  0.8183908 ]
 [ 0.8183908  24.75402299]]


Pearsons correlation: 0.035
Samples are uncorrelated (fail to reject H0) p=0.855
Spearmans correlation: -0.039
Samples are uncorrelated (fail to reject H0) p=0.840
Kendall correlation coefficient: -0.005
Samples are uncorrelated (fail to reject H0) p=0.971
data1: mean=9.208 stdv=2.685
data2: mean=2153.521 stdv=2386.795
covarience value :
[[7.35992908e+00 2.37795301e+03]
 [2.37795301e+03 5.81800000e+06]]


Pearsons correlation: 0.363
Samples are correlated (reject H0) p=0.011
Spearmans correlation: 0.316
Samples are correlated (reject H0) p=0.029
Kendall correlation coefficient: 0.231
Samples are correlated (reject H0) p=0.027
data1: mean=31.105 stdv=0.552
data2: mean=11.263 stdv=12.669
covarience value :
[[ 3.21637427e-01 -2.92397661e-02]
 [-2.92397661e-02  1.69426901e+02]]


Pearsons correlation: -0.004
Samples are uncorrelated (fail to reject H0) p=0.987
Spearmans correlation: -0.026
Samples are uncorrelated (fail to reject H0) p=0.914
Kendall correlation coefficient: -0.017
Samples are uncorrelated (fail to reject H0) p=0.931
data1: mean=4.912 stdv=5.700
data2: mean=51.618 stdv=37.021
covarience value :
[[  33.47682709   68.7228164 ]
 [  68.7228164  1412.12210339]]


Pearsons correlation: 0.316
Samples are uncorrelated (fail to reject H0) p=0.069
Spearmans correlation: 0.277
Samples are uncorrelated (fail to reject H0) p=0.112
Kendall correlation coefficient: 0.193
Samples are uncorrelated (fail to reject H0) p=0.118
data1: mean=29.167 stdv=0.799
data2: mean=10.667 stdv=10.562
covarience value :
[[  0.6969697   -4.21212121]
 [ -4.21212121 121.6969697 ]]


Pearsons correlation: -0.457
Samples are uncorrelated (fail to reject H0) p=0.135
Spearmans correlation: -0.764
Samples are correlated (reject H0) p=0.004
Kendall correlation coefficient: -0.620
Samples are correlated (reject H0) p=0.012
data1: mean=29.682 stdv=1.519
data2: mean=13.545 stdv=14.080
covarience value :
[[  2.41774892   6.8961039 ]
 [  6.8961039  207.68831169]]


Pearsons correlation: 0.308
Samples are uncorrelated (fail to reject H0) p=0.164
Spearmans correlation: 0.276
Samples are uncorrelated (fail to reject H0) p=0.214
Kendall correlation coefficient: 0.221
Samples are uncorrelated (fail to reject H0) p=0.198
data1: mean=11.400 stdv=4.160
data2: mean=24.800 stdv=19.446
covarience value :
[[ 17.90344828  15.80689655]
 [ 15.80689655 391.2       ]]


Pearsons correlation: 0.189
Samples are uncorrelated (fail to reject H0) p=0.318
Spearmans correlation: 0.220
Samples are uncorrelated (fail to reject H0) p=0.243
Kendall correlation coefficient: 0.170
Samples are uncorrelated (fail to reject H0) p=0.202
data1: mean=0.676 stdv=1.756
data2: mean=42.216 stdv=31.587
covarience value :
[[   3.16966967   19.46096096]
 [  19.46096096 1025.45195195]]


Pearsons correlation: 0.341
Samples are correlated (reject H0) p=0.039
Spearmans correlation: 0.273
Samples are uncorrelated (fail to reject H0) p=0.102
Kendall correlation coefficient: 0.202
Samples are uncorrelated (fail to reject H0) p=0.098
data1: mean=29.000 stdv=3.813
data2: mean=129.108 stdv=240.423
covarience value :
[[1.49444444e+01 2.33444444e+02]
 [2.33444444e+02 5.94089324e+04]]


Pearsons correlation: 0.248
Samples are uncorrelated (fail to reject H0) p=0.139
Spearmans correlation: 0.439
Samples are correlated (reject H0) p=0.007
Kendall correlation coefficient: 0.324
Samples are correlated (reject H0) p=0.007
data1: mean=27.935 stdv=1.342
data2: mean=80.355 stdv=60.159
covarience value :
[[ 1.86236559e+00 -1.89763441e+01]
 [-1.89763441e+01  3.73976989e+03]]


Pearsons correlation: -0.227
Samples are uncorrelated (fail to reject H0) p=0.219
Spearmans correlation: -0.279
Samples are uncorrelated (fail to reject H0) p=0.128
Kendall correlation coefficient: -0.204
Samples are uncorrelated (fail to reject H0) p=0.139
data1: mean=13.458 stdv=4.817
data2: mean=1260.417 stdv=1020.358
covarience value :
[[2.37003546e+01 2.71916667e+03]
 [2.71916667e+03 1.06328246e+06]]


Pearsons correlation: 0.542
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.576
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.420
Samples are correlated (reject H0) p=0.000
data1: mean=23.838 stdv=3.507
data2: mean=27.865 stdv=24.624
covarience value :
[[ 12.63963964  23.00525526]
 [ 23.00525526 623.17567568]]


Pearsons correlation: 0.259
Samples are uncorrelated (fail to reject H0) p=0.121
Spearmans correlation: 0.298
Samples are uncorrelated (fail to reject H0) p=0.074
Kendall correlation coefficient: 0.221
Samples are uncorrelated (fail to reject H0) p=0.065
data1: mean=8.562 stdv=2.030
data2: mean=167.625 stdv=140.360
covarience value :
[[4.25403226e+00 1.23862903e+02]
 [1.23862903e+02 2.03365000e+04]]


Pearsons correlation: 0.421
Samples are correlated (reject H0) p=0.016
Spearmans correlation: 0.423
Samples are correlated (reject H0) p=0.016
Kendall correlation coefficient: 0.323
Samples are correlated (reject H0) p=0.014
data1: mean=23.325 stdv=2.778
data2: mean=222.600 stdv=284.840
covarience value :
[[7.91730769e+00 3.17646154e+02]
 [3.17646154e+02 8.32142462e+04]]


Pearsons correlation: 0.391
Samples are correlated (reject H0) p=0.013
Spearmans correlation: 0.379
Samples are correlated (reject H0) p=0.016
Kendall correlation coefficient: 0.279
Samples are correlated (reject H0) p=0.017
data1: mean=16.106 stdv=2.224
data2: mean=2820.106 stdv=2194.295
covarience value :
[[5.05365402e+00 1.23068409e+03]
 [1.23068409e+03 4.91960118e+06]]


Pearsons correlation: 0.247
Samples are uncorrelated (fail to reject H0) p=0.094
Spearmans correlation: 0.262
Samples are uncorrelated (fail to reject H0) p=0.075
Kendall correlation coefficient: 0.175
Samples are uncorrelated (fail to reject H0) p=0.100
data1: mean=8.759 stdv=6.452
data2: mean=67.389 stdv=107.842
covarience value :
[[   42.4126485    355.88784067]
 [  355.88784067 11849.41194969]]


Pearsons correlation: 0.502
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.511
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.372
Samples are correlated (reject H0) p=0.000
data1: mean=16.348 stdv=4.966
data2: mean=15.174 stdv=8.805
covarience value :
[[25.7826087  16.16403162]
 [16.16403162 81.05928854]]


Pearsons correlation: 0.354
Samples are uncorrelated (fail to reject H0) p=0.098
Spearmans correlation: 0.362
Samples are uncorrelated (fail to reject H0) p=0.090
Kendall correlation coefficient: 0.258
Samples are uncorrelated (fail to reject H0) p=0.094
data1: mean=-3.360 stdv=3.804
data2: mean=26.480 stdv=25.022
covarience value :
[[ 15.07333333  22.09666667]
 [ 22.09666667 652.17666667]]


Pearsons correlation: 0.223
Samples are uncorrelated (fail to reject H0) p=0.284
Spearmans correlation: 0.402
Samples are correlated (reject H0) p=0.047
Kendall correlation coefficient: 0.311
Samples are correlated (reject H0) p=0.036
data1: mean=10.517 stdv=5.154
data2: mean=177.121 stdv=203.348
covarience value :
[[ 2.70260133e+01 -9.22915910e+01]
 [-9.22915910e+01  4.20760378e+04]]


Pearsons correlation: -0.087
Samples are uncorrelated (fail to reject H0) p=0.518
Spearmans correlation: 0.122
Samples are uncorrelated (fail to reject H0) p=0.360
Kendall correlation coefficient: 0.098
Samples are uncorrelated (fail to reject H0) p=0.290
data1: mean=21.944 stdv=1.562
data2: mean=18.472 stdv=23.826
covarience value :
[[  2.51111111   4.54126984]
 [  4.54126984 583.91349206]]


Pearsons correlation: 0.119
Samples are uncorrelated (fail to reject H0) p=0.491
Spearmans correlation: 0.232
Samples are uncorrelated (fail to reject H0) p=0.174
Kendall correlation coefficient: 0.171
Samples are uncorrelated (fail to reject H0) p=0.173
data1: mean=9.750 stdv=3.269
data2: mean=13.500 stdv=16.190
covarience value :
[[ 11.4         18.26666667]
 [ 18.26666667 279.6       ]]


Pearsons correlation: 0.324
Samples are uncorrelated (fail to reject H0) p=0.222
Spearmans correlation: 0.385
Samples are uncorrelated (fail to reject H0) p=0.140
Kendall correlation coefficient: 0.275
Samples are uncorrelated (fail to reject H0) p=0.164
data1: mean=5.533 stdv=2.566
data2: mean=18.067 stdv=12.936
covarience value :
[[  6.8091954    1.58390805]
 [  1.58390805 173.09885057]]


Pearsons correlation: 0.046
Samples are uncorrelated (fail to reject H0) p=0.809
Spearmans correlation: 0.091
Samples are uncorrelated (fail to reject H0) p=0.631
Kendall correlation coefficient: 0.064
Samples are uncorrelated (fail to reject H0) p=0.638
data1: mean=17.265 stdv=2.893
data2: mean=15.912 stdv=12.876
covarience value :
[[  8.62477718  15.29679144]
 [ 15.29679144 170.81016043]]


Pearsons correlation: 0.399
Samples are correlated (reject H0) p=0.020
Spearmans correlation: 0.285
Samples are uncorrelated (fail to reject H0) p=0.102
Kendall correlation coefficient: 0.230
Samples are uncorrelated (fail to reject H0) p=0.072
data1: mean=6.481 stdv=2.644
data2: mean=31.222 stdv=23.638
covarience value :
[[  7.25925926 -11.53418803]
 [-11.53418803 580.25641026]]


Pearsons correlation: -0.178
Samples are uncorrelated (fail to reject H0) p=0.375
Spearmans correlation: -0.107
Samples are uncorrelated (fail to reject H0) p=0.594
Kendall correlation coefficient: -0.036
Samples are uncorrelated (fail to reject H0) p=0.799
data1: mean=8.903 stdv=3.256
data2: mean=91.710 stdv=75.044
covarience value :
[[  10.95698925  108.67096774]
 [ 108.67096774 5819.34623656]]


Pearsons correlation: 0.430
Samples are correlated (reject H0) p=0.016
Spearmans correlation: 0.427
Samples are correlated (reject H0) p=0.016
Kendall correlation coefficient: 0.315
Samples are correlated (reject H0) p=0.017
data1: mean=34.214 stdv=1.909
data2: mean=90.119 stdv=76.365
covarience value :
[[ 3.73344948e+00 -3.18815331e-01]
 [-3.18815331e-01  5.97381475e+03]]


Pearsons correlation: -0.002
Samples are uncorrelated (fail to reject H0) p=0.989
Spearmans correlation: -0.004
Samples are uncorrelated (fail to reject H0) p=0.978
Kendall correlation coefficient: -0.017
Samples are uncorrelated (fail to reject H0) p=0.886
data1: mean=15.481 stdv=1.258
data2: mean=8.926 stdv=5.395
covarience value :
[[ 1.64387464 -0.19373219]
 [-0.19373219 30.22507123]]


Pearsons correlation: -0.027
Samples are uncorrelated (fail to reject H0) p=0.892
Spearmans correlation: 0.017
Samples are uncorrelated (fail to reject H0) p=0.934
Kendall correlation coefficient: 0.010
Samples are uncorrelated (fail to reject H0) p=0.948
data1: mean=30.200 stdv=2.786
data2: mean=1.200 stdv=0.400
covarience value :
[[ 9.7 -0.8]
 [-0.8  0.2]]


Pearsons correlation: -0.574
Samples are uncorrelated (fail to reject H0) p=0.311
Spearmans correlation: -0.707
Samples are uncorrelated (fail to reject H0) p=0.182
Kendall correlation coefficient: -0.632
Samples are uncorrelated (fail to reject H0) p=0.157
data1: mean=27.895 stdv=0.852
data2: mean=12.842 stdv=8.375
covarience value :
[[ 0.76608187 -3.35087719]
 [-3.35087719 74.02923977]]


Pearsons correlation: -0.445
Samples are uncorrelated (fail to reject H0) p=0.056
Spearmans correlation: -0.600
Samples are correlated (reject H0) p=0.007
Kendall correlation coefficient: -0.469
Samples are correlated (reject H0) p=0.012
data1: mean=29.875 stdv=2.859
data2: mean=76.219 stdv=78.273
covarience value :
[[   8.43548387  143.96370968]
 [ 143.96370968 6324.30544355]]


Pearsons correlation: 0.623
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.558
Samples are correlated (reject H0) p=0.001
Kendall correlation coefficient: 0.420
Samples are correlated (reject H0) p=0.001
data1: mean=13.320 stdv=4.730
data2: mean=38.600 stdv=40.161
covarience value :
[[  23.31        -78.95      ]
 [ -78.95       1680.08333333]]


Pearsons correlation: -0.399
Samples are correlated (reject H0) p=0.048
Spearmans correlation: -0.411
Samples are correlated (reject H0) p=0.041
Kendall correlation coefficient: -0.302
Samples are correlated (reject H0) p=0.039
data1: mean=32.421 stdv=4.393
data2: mean=12.263 stdv=8.577
covarience value :
[[20.36842105  0.82748538]
 [ 0.82748538 77.64912281]]


Pearsons correlation: 0.021
Samples are uncorrelated (fail to reject H0) p=0.933
Spearmans correlation: 0.038
Samples are uncorrelated (fail to reject H0) p=0.879
Kendall correlation coefficient: 0.024
Samples are uncorrelated (fail to reject H0) p=0.887
data1: mean=18.433 stdv=2.362
data2: mean=37.333 stdv=35.713
covarience value :
[[   5.77126437  -28.08045977]
 [ -28.08045977 1319.40229885]]


Pearsons correlation: -0.322
Samples are uncorrelated (fail to reject H0) p=0.083
Spearmans correlation: -0.319
Samples are uncorrelated (fail to reject H0) p=0.085
Kendall correlation coefficient: -0.198
Samples are uncorrelated (fail to reject H0) p=0.150
data1: mean=9.579 stdv=2.148
data2: mean=498.053 stdv=432.032
covarience value :
[[4.73684211e+00 4.82968706e+02]
 [4.82968706e+02 1.91696376e+05]]


Pearsons correlation: 0.507
Samples are correlated (reject H0) p=0.001
Spearmans correlation: 0.467
Samples are correlated (reject H0) p=0.003
Kendall correlation coefficient: 0.360
Samples are correlated (reject H0) p=0.003
data1: mean=16.923 stdv=1.880
data2: mean=42.538 stdv=34.070
covarience value :
[[   3.67384615  -22.07692308]
 [ -22.07692308 1207.21846154]]


Pearsons correlation: -0.332
Samples are uncorrelated (fail to reject H0) p=0.098
Spearmans correlation: -0.384
Samples are uncorrelated (fail to reject H0) p=0.053
Kendall correlation coefficient: -0.303
Samples are correlated (reject H0) p=0.041
data1: mean=39.364 stdv=1.666
data2: mean=10.818 stdv=9.423
covarience value :
[[ 2.90909091 -4.69264069]
 [-4.69264069 93.01298701]]


Pearsons correlation: -0.285
Samples are uncorrelated (fail to reject H0) p=0.198
Spearmans correlation: -0.342
Samples are uncorrelated (fail to reject H0) p=0.119
Kendall correlation coefficient: -0.284
Samples are uncorrelated (fail to reject H0) p=0.095
data1: mean=8.846 stdv=5.238
data2: mean=21.923 stdv=16.518
covarience value :
[[ 28.53538462  36.06769231]
 [ 36.06769231 283.75384615]]


Pearsons correlation: 0.401
Samples are correlated (reject H0) p=0.042
Spearmans correlation: 0.387
Samples are uncorrelated (fail to reject H0) p=0.051
Kendall correlation coefficient: 0.259
Samples are uncorrelated (fail to reject H0) p=0.069
data1: mean=3.350 stdv=3.062
data2: mean=146.625 stdv=102.788
covarience value :
[[9.61794872e+00 5.26474359e+01]
 [5.26474359e+01 1.08361891e+04]]


Pearsons correlation: 0.163
Samples are uncorrelated (fail to reject H0) p=0.315
Spearmans correlation: 0.059
Samples are uncorrelated (fail to reject H0) p=0.719
Kendall correlation coefficient: 0.043
Samples are uncorrelated (fail to reject H0) p=0.706
data1: mean=25.379 stdv=1.690
data2: mean=11.414 stdv=8.755
covarience value :
[[ 2.95812808  0.55172414]
 [ 0.55172414 79.39408867]]


Pearsons correlation: 0.036
Samples are uncorrelated (fail to reject H0) p=0.853
Spearmans correlation: 0.017
Samples are uncorrelated (fail to reject H0) p=0.929
Kendall correlation coefficient: 0.017
Samples are uncorrelated (fail to reject H0) p=0.908
data1: mean=22.406 stdv=3.587
data2: mean=117.688 stdv=127.650
covarience value :
[[ 1.32812500e+01 -6.28689516e+01]
 [-6.28689516e+01  1.68200927e+04]]


Pearsons correlation: -0.133
Samples are uncorrelated (fail to reject H0) p=0.468
Spearmans correlation: 0.093
Samples are uncorrelated (fail to reject H0) p=0.613
Kendall correlation coefficient: 0.021
Samples are uncorrelated (fail to reject H0) p=0.870
data1: mean=32.654 stdv=0.917
data2: mean=76.462 stdv=64.695
covarience value :
[[8.75384615e-01 2.82061538e+01]
 [2.82061538e+01 4.35289846e+03]]


Pearsons correlation: 0.457
Samples are correlated (reject H0) p=0.019
Spearmans correlation: 0.540
Samples are correlated (reject H0) p=0.004
Kendall correlation coefficient: 0.459
Samples are correlated (reject H0) p=0.003
data1: mean=31.000 stdv=1.000
data2: mean=1.000 stdv=0.000
covarience value :
[[2. 0.]
 [0. 0.]]


C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\stats.py:3508: PearsonRConstantInputWarning:

An input array is constant; the correlation coefficent is not defined.

C:\Users\USER\.conda\envs\DAND\lib\site-packages\numpy\lib\function_base.py:2534: RuntimeWarning:

invalid value encountered in true_divide

C:\Users\USER\.conda\envs\DAND\lib\site-packages\numpy\lib\function_base.py:2535: RuntimeWarning:

invalid value encountered in true_divide

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning:

invalid value encountered in greater

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning:

invalid value encountered in less

C:\Users\USER\.conda\envs\DAND\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning:

invalid value encountered in less_equal



Pearsons correlation: nan
Samples are correlated (reject H0) p=nan
Spearmans correlation: nan
Samples are correlated (reject H0) p=nan
Kendall correlation coefficient: nan
Samples are correlated (reject H0) p=nan
data1: mean=37.913 stdv=3.562
data2: mean=4.913 stdv=3.586
covarience value :
[[13.26482213 -0.28063241]
 [-0.28063241 13.44664032]]


Pearsons correlation: -0.021
Samples are uncorrelated (fail to reject H0) p=0.924
Spearmans correlation: -0.022
Samples are uncorrelated (fail to reject H0) p=0.922
Kendall correlation coefficient: -0.013
Samples are uncorrelated (fail to reject H0) p=0.936
data1: mean=25.897 stdv=0.845
data2: mean=88.310 stdv=112.233
covarience value :
[[ 7.38916256e-01 -5.35381773e+01]
 [-5.35381773e+01  1.30460788e+04]]


Pearsons correlation: -0.545
Samples are correlated (reject H0) p=0.002
Spearmans correlation: -0.329
Samples are uncorrelated (fail to reject H0) p=0.081
Kendall correlation coefficient: -0.272
Samples are uncorrelated (fail to reject H0) p=0.068
data1: mean=32.441 stdv=1.265
data2: mean=107.618 stdv=139.452
covarience value :
[[1.64795009e+00 7.03253119e+01]
 [7.03253119e+01 2.00362433e+04]]


Pearsons correlation: 0.387
Samples are correlated (reject H0) p=0.024
Spearmans correlation: 0.391
Samples are correlated (reject H0) p=0.022
Kendall correlation coefficient: 0.293
Samples are correlated (reject H0) p=0.027
data1: mean=8.562 stdv=3.162
data2: mean=137.906 stdv=131.714
covarience value :
[[1.03185484e+01 8.28629032e-01]
 [8.28629032e-01 1.79082167e+04]]


Pearsons correlation: 0.002
Samples are uncorrelated (fail to reject H0) p=0.992
Spearmans correlation: 0.054
Samples are uncorrelated (fail to reject H0) p=0.768
Kendall correlation coefficient: 0.053
Samples are uncorrelated (fail to reject H0) p=0.683
data1: mean=18.031 stdv=2.580
data2: mean=366.562 stdv=329.980
covarience value :
[[ 6.86995968e+00 -4.85665323e+01]
 [-4.85665323e+01  1.12399222e+05]]


Pearsons correlation: -0.055
Samples are uncorrelated (fail to reject H0) p=0.764
Spearmans correlation: -0.036
Samples are uncorrelated (fail to reject H0) p=0.846
Kendall correlation coefficient: -0.019
Samples are uncorrelated (fail to reject H0) p=0.883
data1: mean=24.938 stdv=1.784
data2: mean=57.250 stdv=79.227
covarience value :
[[ 3.28629032e+00 -8.50000000e+00]
 [-8.50000000e+00  6.47935484e+03]]


Pearsons correlation: -0.058
Samples are uncorrelated (fail to reject H0) p=0.751
Spearmans correlation: 0.090
Samples are uncorrelated (fail to reject H0) p=0.625
Kendall correlation coefficient: 0.078
Samples are uncorrelated (fail to reject H0) p=0.561
data1: mean=13.735 stdv=4.354
data2: mean=119.324 stdv=129.406
covarience value :
[[   19.53386809  -181.97237077]
 [ -181.97237077 17253.43761141]]


Pearsons correlation: -0.313
Samples are uncorrelated (fail to reject H0) p=0.071
Spearmans correlation: -0.118
Samples are uncorrelated (fail to reject H0) p=0.507
Kendall correlation coefficient: -0.068
Samples are uncorrelated (fail to reject H0) p=0.581
data1: mean=5.097 stdv=3.276
data2: mean=204.548 stdv=261.676
covarience value :
[[1.10903226e+01 1.63011828e+02]
 [1.63011828e+02 7.07569892e+04]]


Pearsons correlation: 0.184
Samples are uncorrelated (fail to reject H0) p=0.322
Spearmans correlation: 0.277
Samples are uncorrelated (fail to reject H0) p=0.132
Kendall correlation coefficient: 0.230
Samples are uncorrelated (fail to reject H0) p=0.078
data1: mean=25.600 stdv=1.744
data2: mean=5.250 stdv=4.311
covarience value :
[[ 3.2        -1.94736842]
 [-1.94736842 19.56578947]]


Pearsons correlation: -0.246
Samples are uncorrelated (fail to reject H0) p=0.296
Spearmans correlation: -0.303
Samples are uncorrelated (fail to reject H0) p=0.193
Kendall correlation coefficient: -0.283
Samples are uncorrelated (fail to reject H0) p=0.109
data1: mean=12.720 stdv=2.522
data2: mean=10.640 stdv=7.413
covarience value :
[[ 6.62666667 -2.355     ]
 [-2.355      57.24      ]]


Pearsons correlation: -0.121
Samples are uncorrelated (fail to reject H0) p=0.565
Spearmans correlation: -0.306
Samples are uncorrelated (fail to reject H0) p=0.136
Kendall correlation coefficient: -0.227
Samples are uncorrelated (fail to reject H0) p=0.138
data1: mean=27.967 stdv=3.136
data2: mean=86.833 stdv=67.264
covarience value :
[[  10.17126437   47.82183908]
 [  47.82183908 4680.41954023]]


Pearsons correlation: 0.219
Samples are uncorrelated (fail to reject H0) p=0.245
Spearmans correlation: 0.127
Samples are uncorrelated (fail to reject H0) p=0.503
Kendall correlation coefficient: 0.080
Samples are uncorrelated (fail to reject H0) p=0.551
data1: mean=23.200 stdv=1.720
data2: mean=9.040 stdv=5.459
covarience value :
[[ 3.08333333  0.075     ]
 [ 0.075      31.04      ]]


Pearsons correlation: 0.008
Samples are uncorrelated (fail to reject H0) p=0.971
Spearmans correlation: 0.042
Samples are uncorrelated (fail to reject H0) p=0.843
Kendall correlation coefficient: 0.011
Samples are uncorrelated (fail to reject H0) p=0.943
data1: mean=12.964 stdv=4.939
data2: mean=78.571 stdv=90.717
covarience value :
[[  25.29497354 -126.12698413]
 [-126.12698413 8534.32804233]]


Pearsons correlation: -0.271
Samples are uncorrelated (fail to reject H0) p=0.162
Spearmans correlation: -0.066
Samples are uncorrelated (fail to reject H0) p=0.738
Kendall correlation coefficient: -0.038
Samples are uncorrelated (fail to reject H0) p=0.781
data1: mean=30.250 stdv=0.785
data2: mean=24.321 stdv=26.650
covarience value :
[[6.27272727e-01 9.75454545e+00]
 [9.75454545e+00 7.23131169e+02]]


Pearsons correlation: 0.458
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.535
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.436
Samples are correlated (reject H0) p=0.000
data1: mean=10.600 stdv=3.895
data2: mean=17.800 stdv=12.734
covarience value :
[[ 15.69655172  10.08965517]
 [ 10.08965517 167.75172414]]


Pearsons correlation: 0.197
Samples are uncorrelated (fail to reject H0) p=0.298
Spearmans correlation: 0.084
Samples are uncorrelated (fail to reject H0) p=0.659
Kendall correlation coefficient: 0.044
Samples are uncorrelated (fail to reject H0) p=0.745
data1: mean=9.733 stdv=4.106
data2: mean=34.033 stdv=15.913
covarience value :
[[ 17.44367816  13.73333333]
 [ 13.73333333 261.96436782]]


Pearsons correlation: 0.203
Samples are uncorrelated (fail to reject H0) p=0.282
Spearmans correlation: 0.182
Samples are uncorrelated (fail to reject H0) p=0.336
Kendall correlation coefficient: 0.125
Samples are uncorrelated (fail to reject H0) p=0.349
data1: mean=28.793 stdv=2.821
data2: mean=58.138 stdv=63.081
covarience value :
[[   8.24137931   14.74384236]
 [  14.74384236 4121.26600985]]


Pearsons correlation: 0.080
Samples are uncorrelated (fail to reject H0) p=0.680
Spearmans correlation: 0.252
Samples are uncorrelated (fail to reject H0) p=0.188
Kendall correlation coefficient: 0.196
Samples are uncorrelated (fail to reject H0) p=0.154
data1: mean=16.721 stdv=4.390
data2: mean=3178.488 stdv=3237.654
covarience value :
[[ 1.97297896e+01 -2.46986047e+03]
 [-2.46986047e+03  1.07319821e+07]]


Pearsons correlation: -0.170
Samples are uncorrelated (fail to reject H0) p=0.277
Spearmans correlation: -0.121
Samples are uncorrelated (fail to reject H0) p=0.438
Kendall correlation coefficient: -0.087
Samples are uncorrelated (fail to reject H0) p=0.425
data1: mean=5.400 stdv=2.615
data2: mean=180.125 stdv=163.681
covarience value :
[[7.01538462e+00 7.00256410e+01]
 [7.00256410e+01 2.74783173e+04]]


Pearsons correlation: 0.159
Samples are uncorrelated (fail to reject H0) p=0.326
Spearmans correlation: 0.129
Samples are uncorrelated (fail to reject H0) p=0.429
Kendall correlation coefficient: 0.105
Samples are uncorrelated (fail to reject H0) p=0.359
data1: mean=10.244 stdv=4.218
data2: mean=528.317 stdv=472.089
covarience value :
[[1.82390244e+01 4.94220732e+02]
 [4.94220732e+02 2.28440072e+05]]


Pearsons correlation: 0.242
Samples are uncorrelated (fail to reject H0) p=0.127
Spearmans correlation: 0.167
Samples are uncorrelated (fail to reject H0) p=0.296
Kendall correlation coefficient: 0.110
Samples are uncorrelated (fail to reject H0) p=0.326
data1: mean=26.188 stdv=3.039
data2: mean=7.562 stdv=7.494
covarience value :
[[ 9.43218085  6.76462766]
 [ 6.76462766 57.35771277]]


Pearsons correlation: 0.291
Samples are correlated (reject H0) p=0.045
Spearmans correlation: 0.350
Samples are correlated (reject H0) p=0.015
Kendall correlation coefficient: 0.234
Samples are correlated (reject H0) p=0.031
data1: mean=35.439 stdv=1.250
data2: mean=53.683 stdv=53.577
covarience value :
[[1.60243902e+00 1.77176829e+01]
 [1.77176829e+01 2.94222195e+03]]


Pearsons correlation: 0.258
Samples are uncorrelated (fail to reject H0) p=0.103
Spearmans correlation: 0.226
Samples are uncorrelated (fail to reject H0) p=0.156
Kendall correlation coefficient: 0.173
Samples are uncorrelated (fail to reject H0) p=0.153
data1: mean=28.091 stdv=0.733
data2: mean=4.773 stdv=7.914
covarience value :
[[ 0.56277056  1.35497835]
 [ 1.35497835 65.61255411]]


Pearsons correlation: 0.223
Samples are uncorrelated (fail to reject H0) p=0.319
Spearmans correlation: -0.098
Samples are uncorrelated (fail to reject H0) p=0.665
Kendall correlation coefficient: -0.080
Samples are uncorrelated (fail to reject H0) p=0.663
data1: mean=17.593 stdv=3.258
data2: mean=22.074 stdv=20.717
covarience value :
[[ 11.01994302 -24.6994302 ]
 [-24.6994302  445.68660969]]


Pearsons correlation: -0.352
Samples are uncorrelated (fail to reject H0) p=0.071
Spearmans correlation: -0.244
Samples are uncorrelated (fail to reject H0) p=0.219
Kendall correlation coefficient: -0.155
Samples are uncorrelated (fail to reject H0) p=0.281
data1: mean=13.760 stdv=5.014
data2: mean=1208.680 stdv=1157.404
covarience value :
[[ 2.61900000e+01 -1.59724667e+03]
 [-1.59724667e+03  1.39540039e+06]]


Pearsons correlation: -0.264
Samples are uncorrelated (fail to reject H0) p=0.202
Spearmans correlation: -0.228
Samples are uncorrelated (fail to reject H0) p=0.274
Kendall correlation coefficient: -0.124
Samples are uncorrelated (fail to reject H0) p=0.397
data1: mean=20.809 stdv=4.880
data2: mean=7793.830 stdv=10858.107
covarience value :
[[2.43320999e+01 3.67084015e+04]
 [3.67084015e+04 1.20461488e+08]]


Pearsons correlation: 0.678
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.709
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.535
Samples are correlated (reject H0) p=0.000
data1: mean=9.091 stdv=3.988
data2: mean=59.955 stdv=54.568
covarience value :
[[  16.65800866 -109.23376623]
 [-109.23376623 3119.47402597]]


Pearsons correlation: -0.479
Samples are correlated (reject H0) p=0.024
Spearmans correlation: -0.410
Samples are uncorrelated (fail to reject H0) p=0.058
Kendall correlation coefficient: -0.308
Samples are uncorrelated (fail to reject H0) p=0.050
data1: mean=26.367 stdv=3.773
data2: mean=69.067 stdv=89.582
covarience value :
[[  14.72298851   21.69885057]
 [  21.69885057 8301.71954023]]


Pearsons correlation: 0.062
Samples are uncorrelated (fail to reject H0) p=0.745
Spearmans correlation: 0.369
Samples are correlated (reject H0) p=0.045
Kendall correlation coefficient: 0.290
Samples are correlated (reject H0) p=0.031
data1: mean=7.977 stdv=8.329
data2: mean=1215.744 stdv=1607.258
covarience value :
[[7.10232558e+01 7.37573200e+03]
 [7.37573200e+03 2.64478634e+06]]


Pearsons correlation: 0.538
Samples are correlated (reject H0) p=0.000
Spearmans correlation: 0.638
Samples are correlated (reject H0) p=0.000
Kendall correlation coefficient: 0.464
Samples are correlated (reject H0) p=0.000
data1: mean=28.286 stdv=3.442
data2: mean=15.000 stdv=9.979
covarience value :
[[ 12.28571429  -0.51851852]
 [ -0.51851852 103.25925926]]


Pearsons correlation: -0.015
Samples are uncorrelated (fail to reject H0) p=0.941
Spearmans correlation: -0.028
Samples are uncorrelated (fail to reject H0) p=0.886
Kendall correlation coefficient: -0.014
Samples are uncorrelated (fail to reject H0) p=0.921
data1: mean=17.864 stdv=5.320
data2: mean=20.773 stdv=26.483
covarience value :
[[ 29.64718615  17.63419913]
 [ 17.63419913 734.75541126]]


Pearsons correlation: 0.119
Samples are uncorrelated (fail to reject H0) p=0.596
Spearmans correlation: 0.377
Samples are uncorrelated (fail to reject H0) p=0.084
Kendall correlation coefficient: 0.283
Samples are uncorrelated (fail to reject H0) p=0.073
data1: mean=24.850 stdv=1.931
data2: mean=8.350 stdv=6.295
covarience value :
[[ 3.92368421  1.10789474]
 [ 1.10789474 41.71315789]]


Pearsons correlation: 0.087
Samples are uncorrelated (fail to reject H0) p=0.717
Spearmans correlation: 0.049
Samples are uncorrelated (fail to reject H0) p=0.838
Kendall correlation coefficient: 0.037
Samples are uncorrelated (fail to reject H0) p=0.838
data1: mean=26.378 stdv=4.658
data2: mean=6.568 stdv=4.722
covarience value :
[[22.2972973   6.86261261]
 [ 6.86261261 22.91891892]]


Pearsons correlation: 0.304
Samples are uncorrelated (fail to reject H0) p=0.068
Spearmans correlation: 0.268
Samples are uncorrelated (fail to reject H0) p=0.109
Kendall correlation coefficient: 0.193
Samples are uncorrelated (fail to reject H0) p=0.110
data1: mean=-0.393 stdv=2.540
data2: mean=9.071 stdv=8.771
covarience value :
[[ 6.69179894 -3.15608466]
 [-3.15608466 79.77248677]]


Pearsons correlation: -0.137
Samples are uncorrelated (fail to reject H0) p=0.488
Spearmans correlation: -0.129
Samples are uncorrelated (fail to reject H0) p=0.513
Kendall correlation coefficient: -0.098
Samples are uncorrelated (fail to reject H0) p=0.503


Empty DataFrame
Columns: []
Index: []

In [ ]:
dfg.head()

# Previous approach

# Reading datasests for specific countrys (might change later)

In [ ]:
dataset = pd.read_csv('country_model3.csv')
dataset
Bd2 = dataset.iloc[1:71, 4:5]
Bd1 = dataset.iloc[1:71, 8:9]

Br2 = dataset.iloc[72:142, 4:5]
Br1 = dataset.iloc[72:142, 8:9]

Cn2 = dataset.iloc[143:213, 4:5]
Cn1 = dataset.iloc[143:213, 8:9]

In2 = dataset.iloc[214:284, 4:5]
In1 = dataset.iloc[214:284, 8:9]

It2 = dataset.iloc[285:355, 4:5]
It1 = dataset.iloc[285:355, 8:9]


Uk2 = dataset.iloc[356:426, 4:5]
Uk1 = dataset.iloc[356:426, 8:9]

Us2 = dataset.iloc[427:497,4:5]
Us1 = dataset.iloc[427:497, 8:9]


Bangladesh

In [ ]:
correl(Bd1,Bd2)
countrys.append('Bangladesh')

India

In [ ]:
correl(In1,In2)
countrys.append('India')

USA

In [ ]:
correl(Us1,Us2)
countrys.append('United States')

United Kingdom

In [ ]:
correl(Uk1,Uk2)
countrys.append('United Kingdom')

China

In [ ]:
correl(Cn1,Cn2)
countrys.append('China')

Italy

In [ ]:
correl(It1,It2)
countrys.append('Italy')

Brazil

In [ ]:
correl(Br1,Br2)
countrys.append('Brazil')

In [4]:
len(countrys)

115

In [5]:
print(countrys)

['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Cabo Verde', 'Cambodia', 'Canada', 'Chile', 'China', 'Colombia', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guinea', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Japan', 'Jordan', 'Kazakhstan', 'Korea, South', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Montenegro', 'Morocco', 'Netherlands', 'New Zealand', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Pe

In [7]:
print(correlationp.sort())

None


In [9]:
len(correlationp)

115

In [10]:
print(correlationp)

['-0.0019', '-0.0021', '-0.0040', '-0.0058', '-0.0146', '-0.0210', '-0.0275', '-0.0544', '-0.0547', '-0.0553', '-0.0583', '-0.0782', '-0.0839', '-0.0865', '-0.1064', '-0.1139', '-0.1209', '-0.1330', '-0.1366', '-0.1697', '-0.1777', '-0.2100', '-0.2274', '-0.2461', '-0.2483', '-0.2642', '-0.2715', '-0.2816', '-0.2853', '-0.3130', '-0.3135', '-0.3181', '-0.3218', '-0.3315', '-0.3524', '-0.3989', '-0.4070', '-0.4391', '-0.4450', '-0.4574', '-0.4792', '-0.5453', '-0.5744', '-0.6593', '0.0019', '0.0077', '0.0208', '0.0217', '0.0349', '0.0360', '0.0461', '0.0621', '0.0631', '0.0773', '0.0800', '0.0825', '0.0828', '0.0866', '0.1000', '0.1085', '0.1186', '0.1195', '0.1579', '0.1595', '0.1631', '0.1838', '0.1838', '0.1840', '0.1857', '0.1889', '0.1949', '0.1966', '0.2032', '0.2192', '0.2229', '0.2230', '0.2421', '0.2446', '0.2468', '0.2478', '0.2580', '0.2592', '0.2908', '0.3022', '0.3036', '0.3077', '0.3161', '0.3235', '0.3413', '0.3536', '0.3563', '0.3634', '0.3649', '0.3680', '0.3870', '0.39

In [11]:
print(statistics.median(correlationp))

0.0866


In [12]:
correlations.sort()
correlationk.sort()

In [13]:
print(correlations)

['-0.0009', '-0.0035', '-0.0044', '-0.0216', '-0.0265', '-0.0283', '-0.0358', '-0.0386', '-0.0578', '-0.0661', '-0.0815', '-0.0826', '-0.0881', '-0.0977', '-0.1029', '-0.1075', '-0.1177', '-0.1214', '-0.1289', '-0.1423', '-0.1741', '-0.1906', '-0.2074', '-0.2171', '-0.2275', '-0.2443', '-0.2793', '-0.3034', '-0.3035', '-0.3043', '-0.3065', '-0.3193', '-0.3293', '-0.3419', '-0.3831', '-0.3836', '-0.4099', '-0.4107', '-0.4828', '-0.6000', '-0.6106', '-0.6909', '-0.7071', '-0.7644', '0.0166', '0.0174', '0.0376', '0.0417', '0.0441', '0.0490', '0.0543', '0.0579', '0.0586', '0.0785', '0.0841', '0.0899', '0.0914', '0.0930', '0.1018', '0.1224', '0.1271', '0.1287', '0.1339', '0.1414', '0.1521', '0.1672', '0.1818', '0.2198', '0.2259', '0.2297', '0.2316', '0.2416', '0.2517', '0.2623', '0.2641', '0.2676', '0.2727', '0.2758', '0.2765', '0.2773', '0.2788', '0.2803', '0.2855', '0.2977', '0.3160', '0.3496', '0.3559', '0.3620', '0.3693', '0.3766', '0.3786', '0.3854', '0.3866', '0.3892', '0.3915', '0.40

In [14]:
statistics.median(correlations)

'0.0930'

In [15]:
print(correlationk)

['-0.0050', '-0.0129', '-0.0139', '-0.0166', '-0.0172', '-0.0191', '-0.0263', '-0.0281', '-0.0365', '-0.0378', '-0.0407', '-0.0651', '-0.0682', '-0.0795', '-0.0865', '-0.0895', '-0.0978', '-0.1010', '-0.1238', '-0.1289', '-0.1346', '-0.1408', '-0.1547', '-0.1611', '-0.1979', '-0.2037', '-0.2119', '-0.2168', '-0.2266', '-0.2680', '-0.2718', '-0.2832', '-0.2843', '-0.3025', '-0.3032', '-0.3081', '-0.3322', '-0.4102', '-0.4689', '-0.5237', '-0.6199', '-0.6325', '0.0000', '0.0064', '0.0098', '0.0111', '0.0167', '0.0212', '0.0245', '0.0366', '0.0411', '0.0431', '0.0435', '0.0526', '0.0600', '0.0643', '0.0714', '0.0777', '0.0800', '0.0813', '0.0867', '0.0984', '0.1049', '0.1100', '0.1236', '0.1249', '0.1348', '0.1675', '0.1703', '0.1714', '0.1730', '0.1755', '0.1829', '0.1829', '0.1845', '0.1925', '0.1933', '0.1964', '0.2021', '0.2209', '0.2212', '0.2296', '0.2300', '0.2309', '0.2337', '0.2361', '0.2491', '0.2582', '0.2591', '0.2717', '0.2753', '0.2792', '0.2832', '0.2900', '0.2931', '0.3108

In [16]:
statistics.median(correlationk)

'0.0777'

In [14]:
print(commentpearson)

['uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'correlated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'correlated', 'correlated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'correlated', 'correlated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'correlated', 'correlated', 'uncorrelated', 'correlated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'uncorrelated', 'correlated', 'uncorrelated', 'correlated', 'uncorrelated',

# Making dataframe for findings

In [26]:
dframe = pd.DataFrame({'Country name':countrys, 'Pearson\'s correlation':correlationp, 'P-value of pearson\'s correlation': pearp, 'Comment on pearson\'s correlation':commentpearson,'Spearsman\'s correlation':correlations,'P-value of spearman\'s correlation':spearp, 'Comment on spearsman\'s correlation':commentspearsman, 'Kendall\'s correlation':correlationk,'P-value of kendall\'s correlation':kendallp, 'Comment on kendall\'s correlation':commentkendall})
dframe

Country name Pearson's correlation  \
0           Afghanistan                 0.402   
1               Albania                 0.245   
2               Algeria                -0.114   
3               Andorra                -0.055   
4             Argentina                -0.282   
..                  ...                   ...   
110             Uruguay                -0.015   
111          Uzbekistan                 0.119   
112           Venezuela                 0.087   
113             Vietnam                 0.304   
114  West Bank and Gaza                -0.137   

    P-value of pearson's correlation Comment on pearson's correlation  \
0                              0.057                     uncorrelated   
1                              0.201                     uncorrelated   
2                              0.528                     uncorrelated   
3                              0.809                     uncorrelated   
4                              0.147                     uncorrelated   
..                               ...                              ...   
110                            0.941                     uncorrelated   
111                            0.596                     uncorrelated   
112                            0.717                     uncorrelated   
113                            0.068                     uncorrelated   
114                            0.488                     uncorrelated   

    Spearsman's correlation P-value of spearman's correlation  \
0                     0.540                             0.008   
1                     0.389                             0.037   
2                    -0.142                             0.430   
3                    -0.058                             0.798   
4                    -0.304                             0.116   
..                      ...                               ...   
110                  -0.028                             0.886   
111                   0.377                             0.084   
112                   0.049                             0.838   
113                   0.268                             0.109   
114                  -0.129                             0.513   

    Comment on spearsman's correlation Kendall's correlation  \
0                           correlated                 0.412   
1                           correlated                 0.272   
2                         uncorrelated                -0.090   
3                         uncorrelated                -0.041   
4                         uncorrelated                -0.217   
..                                 ...                   ...   
110                       uncorrelated                -0.014   
111                       uncorrelated                 0.283   
112                       uncorrelated                 0.037   
113                       uncorrelated                 0.193   
114                       uncorrelated                -0.098   

    P-value of kendall's correlation Comment on kendall's correlation  
0                              0.009                       correlated  
1                              0.047                       correlated  
2                              0.482                     uncorrelated  
3                              0.798                     uncorrelated  
4                              0.116                     uncorrelated  
..                               ...                              ...  
110                            0.921                     uncorrelated  
111                            0.073                     uncorrelated  
112                            0.838                     uncorrelated  
113                            0.110                     uncorrelated  
114                            0.503                     uncorrelated  

[115 rows x 10 columns]

# Making csv for findings

In [27]:
 dframe.to_csv(r'temperaturelatonfindings.csv', index=False)

# plotted using plotly ( But plotly doesn't support dashed grid line so might change later with Matplotlib

In [ ]:
colors = ['olive','olive','olive','olive','olive','olive','olive']

go.Figure([go.Bar(
    x=countrys, y= correlationp,
    text= correlationp,
    marker_color= colors,
    textposition='auto',textfont=dict(
        family="times new roman",
        size = 22,
        color="black"
    )
)]).update_layout( bargap=0.2,
    width= 600, height=800,
    xaxis = dict(title='Country Name'), yaxis = dict(title='Pearson\'s correlation coefficient'),font=dict(family="times new roman", size= 22 , color = "black")
).update_xaxes(showline=True, linewidth=2, linecolor='black',gridcolor='lightgrey',ticks="inside",ticklen=10,tickwidth=2,mirror=True).update_yaxes(showline=True, linewidth=2, linecolor='black',gridcolor='lightgrey',ticks="inside",ticklen=6,tickwidth=2, mirror=True).show(displayModeBar= True)

# Tried with matplotlib but wrong graph

In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.bar(countrys,correlationp)
plt.show()